local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[613351] = {
		readable = "Discarded Energy Pike",
		model = 5928059,
		text = {
			en = "Discarded Energy Pike",
			es = "Discarded Energy Pike",
			mx = "Discarded Energy Pike",
			de = "Discarded Energy Pike",
			fr = "Discarded Energy Pike",
			it = "Discarded Energy Pike",
			pt = "Discarded Energy Pike",
			ru = "Discarded Energy Pike",
			ko = "Discarded Energy Pike",
			cn = "Discarded Energy Pike",
			tw = "Discarded Energy Pike",
		},
	},
	[613368] = {
		readable = "Quivering Egg",
		model = 7302402,
		text = {
			en = "Quivering Egg",
			es = "Quivering Egg",
			mx = "Quivering Egg",
			de = "Quivering Egg",
			fr = "Quivering Egg",
			it = "Quivering Egg",
			pt = "Quivering Egg",
			ru = "Quivering Egg",
			ko = "Quivering Egg",
			cn = "Quivering Egg",
			tw = "Quivering Egg",
		},
	},
	[613438] = {
		readable = "Shade Lily Cluster",
		model = 4005589,
		text = {
			en = "Shade Lily Cluster",
			es = "Shade Lily Cluster",
			mx = "Shade Lily Cluster",
			de = "Shade Lily Cluster",
			fr = "Shade Lily Cluster",
			it = "Shade Lily Cluster",
			pt = "Shade Lily Cluster",
			ru = "Shade Lily Cluster",
			ko = "Shade Lily Cluster",
			cn = "Shade Lily Cluster",
			tw = "Shade Lily Cluster",
		},
	},
	[613439] = {
		readable = "Dragonhawk Fern",
		model = 6103434,
		text = {
			en = "Dragonhawk Fern",
			es = "Dragonhawk Fern",
			mx = "Dragonhawk Fern",
			de = "Dragonhawk Fern",
			fr = "Dragonhawk Fern",
			it = "Dragonhawk Fern",
			pt = "Dragonhawk Fern",
			ru = "Dragonhawk Fern",
			ko = "Dragonhawk Fern",
			cn = "Dragonhawk Fern",
			tw = "Dragonhawk Fern",
		},
	},
	[613697] = {
		readable = "Gift of the Phoenix",
		model = 4324806,
		text = {
			en = "Gift of the Phoenix",
			es = "Gift of the Phoenix",
			mx = "Gift of the Phoenix",
			de = "Gift of the Phoenix",
			fr = "Gift of the Phoenix",
			it = "Gift of the Phoenix",
			pt = "Gift of the Phoenix",
			ru = "Gift of the Phoenix",
			ko = "Gift of the Phoenix",
			cn = "Gift of the Phoenix",
			tw = "Gift of the Phoenix",
		},
	},
	[613708] = {
		readable = "Sunstrider Vessel",
		model = 4324806,
		text = {
			en = "Sunstrider Vessel",
			es = "Sunstrider Vessel",
			mx = "Sunstrider Vessel",
			de = "Sunstrider Vessel",
			fr = "Sunstrider Vessel",
			it = "Sunstrider Vessel",
			pt = "Sunstrider Vessel",
			ru = "Sunstrider Vessel",
			ko = "Sunstrider Vessel",
			cn = "Sunstrider Vessel",
			tw = "Sunstrider Vessel",
		},
	},
	[613818] = {
		readable = "Tarnished Mural",
		model = 6715099,
		text = {
			en = "Tarnished Mural",
		},
	},
})
do ObjectDB[objectID] = objectData; end
