local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[572038] = {
		readable = "Dried Roses",
		model = 305201,
		text = {
			en = "Dried Roses",
			es = "[Dried Roses]",
			mx = "[Dried Roses]",
			de = "[Dried Roses]",
			fr = "[Dried Roses]",
			it = "[Dried Roses]",
			pt = "[Dried Roses]",
			ru = "[Dried Roses]",
			ko = "[Dried Roses]",
			cn = "[Dried Roses]",
			tw = "[Dried Roses]",
		},
	},
	[572039] = {
		readable = "Clefthoof Hide",
		model = 902697,
		text = {
			en = "Clefthoof Hide",
			es = "[Clefthoof Hide]",
			mx = "[Clefthoof Hide]",
			de = "[Clefthoof Hide]",
			fr = "[Clefthoof Hide]",
			it = "[Clefthoof Hide]",
			pt = "[Clefthoof Hide]",
			ru = "[Clefthoof Hide]",
			ko = "[Clefthoof Hide]",
			cn = "[Clefthoof Hide]",
			tw = "[Clefthoof Hide]",
		},
	},
	[644396] = {
		readable = "Tainted Bone Pile",
		model = 4525135,
		text = {
			en = "Tainted Bone Pile",
			es = "[Tainted Bone Pile]",
			mx = "[Tainted Bone Pile]",
			de = "[Tainted Bone Pile]",
			fr = "[Tainted Bone Pile]",
			it = "[Tainted Bone Pile]",
			pt = "[Tainted Bone Pile]",
			ru = "[Tainted Bone Pile]",
			ko = "[Tainted Bone Pile]",
			cn = "[Tainted Bone Pile]",
			tw = "[Tainted Bone Pile]",
		},
	},
	[645181] = {
		readable = "Exquisite Treasure",
		model = 5647269,
		text = {
			en = "Exquisite Treasure",
			es = "[Exquisite Treasure]",
			mx = "[Exquisite Treasure]",
			de = "[Exquisite Treasure]",
			fr = "[Exquisite Treasure]",
			it = "[Exquisite Treasure]",
			pt = "[Exquisite Treasure]",
			ru = "[Exquisite Treasure]",
			ko = "[Exquisite Treasure]",
			cn = "[Exquisite Treasure]",
			tw = "[Exquisite Treasure]",
		},
	},
	[645182] = {
		readable = "Crystalline Treasure",
		model = 1687827,
		text = {
			en = "Crystalline Treasure",
			es = "[Crystalline Treasure]",
			mx = "[Crystalline Treasure]",
			de = "[Crystalline Treasure]",
			fr = "[Crystalline Treasure]",
			it = "[Crystalline Treasure]",
			pt = "[Crystalline Treasure]",
			ru = "[Crystalline Treasure]",
			ko = "[Crystalline Treasure]",
			cn = "[Crystalline Treasure]",
			tw = "[Crystalline Treasure]",
		},
	},
	[645183] = {
		readable = "Ethereal Treasure",
		model = 196155,
		text = {
			en = "Ethereal Treasure",
			es = "[Ethereal Treasure]",
			mx = "[Ethereal Treasure]",
			de = "[Ethereal Treasure]",
			fr = "[Ethereal Treasure]",
			it = "[Ethereal Treasure]",
			pt = "[Ethereal Treasure]",
			ru = "[Ethereal Treasure]",
			ko = "[Ethereal Treasure]",
			cn = "[Ethereal Treasure]",
			tw = "[Ethereal Treasure]",
		},
	},
	[645184] = {
		readable = "Sculpted Treasure",
		model = 4209086,
		text = {
			en = "Sculpted Treasure",
			es = "[Sculpted Treasure]",
			mx = "[Sculpted Treasure]",
			de = "[Sculpted Treasure]",
			fr = "[Sculpted Treasure]",
			it = "[Sculpted Treasure]",
			pt = "[Sculpted Treasure]",
			ru = "[Sculpted Treasure]",
			ko = "[Sculpted Treasure]",
			cn = "[Sculpted Treasure]",
			tw = "[Sculpted Treasure]",
		},
	},
	[649380] = {
		readable = "Washed Up Kelp",
		model = 1569583,
		text = {
			en = "Washed Up Kelp",
			es = "[Washed Up Kelp]",
			mx = "[Washed Up Kelp]",
			de = "[Washed Up Kelp]",
			fr = "[Washed Up Kelp]",
			it = "[Washed Up Kelp]",
			pt = "[Washed Up Kelp]",
			ru = "[Washed Up Kelp]",
			ko = "[Washed Up Kelp]",
			cn = "[Washed Up Kelp]",
			tw = "[Washed Up Kelp]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
