local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[556121] = {
		readable = "Radiant Glowcap",
		model = 4420056,
		text = {
			en = "Radiant Glowcap",
			es = "Radiant Glowcap",
			mx = "Radiant Glowcap",
			de = "Radiant Glowcap",
			fr = "Radiant Glowcap",
			it = "Radiant Glowcap",
			pt = "Radiant Glowcap",
			ru = "Radiant Glowcap",
			ko = "Radiant Glowcap",
			cn = "Radiant Glowcap",
			tw = "Radiant Glowcap",
		},
	},
	[566020] = {
		readable = "Groffa's Hoard",
		model = 5975175,
		text = {
			en = "Groffa's Hoard",
			es = "Groffa's Hoard",
			mx = "Groffa's Hoard",
			de = "Groffa's Hoard",
			fr = "Groffa's Hoard",
			it = "Groffa's Hoard",
			pt = "Groffa's Hoard",
			ru = "Groffa's Hoard",
			ko = "Groffa's Hoard",
			cn = "Groffa's Hoard",
			tw = "Groffa's Hoard",
		},
	},
	[567976] = {
		readable = "Eagle Feather",
		model = 199708,
		text = {
			en = "Eagle Feather",
			es = "Eagle Feather",
			mx = "Eagle Feather",
			de = "Eagle Feather",
			fr = "Eagle Feather",
			it = "Eagle Feather",
			pt = "Eagle Feather",
			ru = "Eagle Feather",
			ko = "Eagle Feather",
			cn = "Eagle Feather",
			tw = "Eagle Feather",
		},
	},
	[568477] = {
		readable = "Ghostland Pepper",
		model = 6043925,
		text = {
			en = "Ghostland Pepper",
			es = "[Ghostland Pepper]",
			mx = "[Ghostland Pepper]",
			de = "[Ghostland Pepper]",
			fr = "[Ghostland Pepper]",
			it = "[Ghostland Pepper]",
			pt = "[Ghostland Pepper]",
			ru = "[Ghostland Pepper]",
			ko = "[Ghostland Pepper]",
			cn = "[Ghostland Pepper]",
			tw = "[Ghostland Pepper]",
		},
	},
	[568483] = {
		readable = "Naga Scimitar",
		model = 3004113,
		text = {
			en = "Naga Scimitar",
			es = "Naga Scimitar",
			mx = "Naga Scimitar",
			de = "Naga Scimitar",
			fr = "Naga Scimitar",
			it = "Naga Scimitar",
			pt = "Naga Scimitar",
			ru = "Naga Scimitar",
			ko = "Naga Scimitar",
			cn = "Naga Scimitar",
			tw = "Naga Scimitar",
		},
	},
	[571122] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571123] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571124] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571125] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571126] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
		},
	},
})
do ObjectDB[objectID] = objectData; end
