local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[579237] = {
		readable = "Echoes of Our Past--Part 2: Alndust",
		model = 6326920,
		text = {
			en = "Echoes of Our Past--Part 2: Alndust",
			es = "Echoes of Our Past--Part 2: Alndust",
			mx = "Echoes of Our Past--Part 2: Alndust",
			de = "Echoes of Our Past--Part 2: Alndust",
			fr = "Echoes of Our Past--Part 2: Alndust",
			it = "Echoes of Our Past--Part 2: Alndust",
			pt = "Echoes of Our Past--Part 2: Alndust",
			ru = "Echoes of Our Past--Part 2: Alndust",
			ko = "Echoes of Our Past--Part 2: Alndust",
			cn = "Echoes of Our Past--Part 2: Alndust",
			tw = "Echoes of Our Past--Part 2: Alndust",
		},
	},
	[579238] = {
		readable = "Echoes of Our Past--Part 3: Dangerous Memories",
		model = 6326920,
		text = {
			en = "Echoes of Our Past--Part 3: Dangerous Memories",
			es = "Echoes of Our Past--Part 3: Dangerous Memories",
			mx = "Echoes of Our Past--Part 3: Dangerous Memories",
			de = "Echoes of Our Past--Part 3: Dangerous Memories",
			fr = "Echoes of Our Past--Part 3: Dangerous Memories",
			it = "Echoes of Our Past--Part 3: Dangerous Memories",
			pt = "Echoes of Our Past--Part 3: Dangerous Memories",
			ru = "Echoes of Our Past--Part 3: Dangerous Memories",
			ko = "Echoes of Our Past--Part 3: Dangerous Memories",
			cn = "Echoes of Our Past--Part 3: Dangerous Memories",
			tw = "Echoes of Our Past--Part 3: Dangerous Memories",
		},
	},
	[579239] = {
		readable = "Seeker's Trail--Part 1: Call of Aln'hara",
		model = 6326920,
		text = {
			en = "Seeker's Trail--Part 1: Call of Aln'hara",
			es = "Seeker's Trail--Part 1: Call of Aln'hara",
			mx = "Seeker's Trail--Part 1: Call of Aln'hara",
			de = "Seeker's Trail--Part 1: Call of Aln'hara",
			fr = "Seeker's Trail--Part 1: Call of Aln'hara",
			it = "Seeker's Trail--Part 1: Call of Aln'hara",
			pt = "Seeker's Trail--Part 1: Call of Aln'hara",
			ru = "Seeker's Trail--Part 1: Call of Aln'hara",
			ko = "Seeker's Trail--Part 1: Call of Aln'hara",
			cn = "Seeker's Trail--Part 1: Call of Aln'hara",
			tw = "Seeker's Trail--Part 1: Call of Aln'hara",
		},
	},
	[579240] = {
		readable = "Seeker's Trail--Part 2: Seeking Peace",
		model = 6326920,
		text = {
			en = "Seeker's Trail--Part 2: Seeking Peace",
			es = "Seeker's Trail--Part 2: Seeking Peace",
			mx = "Seeker's Trail--Part 2: Seeking Peace",
			de = "Seeker's Trail--Part 2: Seeking Peace",
			fr = "Seeker's Trail--Part 2: Seeking Peace",
			it = "Seeker's Trail--Part 2: Seeking Peace",
			pt = "Seeker's Trail--Part 2: Seeking Peace",
			ru = "Seeker's Trail--Part 2: Seeking Peace",
			ko = "Seeker's Trail--Part 2: Seeking Peace",
			cn = "Seeker's Trail--Part 2: Seeking Peace",
			tw = "Seeker's Trail--Part 2: Seeking Peace",
		},
	},
	[579241] = {
		readable = "Seeker's Trail--Part 3: Unending Mission",
		model = 6326920,
		text = {
			en = "Seeker's Trail--Part 3: Unending Mission",
			es = "Seeker's Trail--Part 3: Unending Mission",
			mx = "Seeker's Trail--Part 3: Unending Mission",
			de = "Seeker's Trail--Part 3: Unending Mission",
			fr = "Seeker's Trail--Part 3: Unending Mission",
			it = "Seeker's Trail--Part 3: Unending Mission",
			pt = "Seeker's Trail--Part 3: Unending Mission",
			ru = "Seeker's Trail--Part 3: Unending Mission",
			ko = "Seeker's Trail--Part 3: Unending Mission",
			cn = "Seeker's Trail--Part 3: Unending Mission",
			tw = "Seeker's Trail--Part 3: Unending Mission",
		},
	},
	[580011] = {
		readable = "Tome of Pain",
		model = 5975157,
		text = {
			en = "Tome of Pain",
			es = "Tome of Pain",
			mx = "Tome of Pain",
			de = "Tome of Pain",
			fr = "Tome of Pain",
			it = "Tome of Pain",
			pt = "Tome of Pain",
		},
	},
})
do ObjectDB[objectID] = objectData; end
