local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[551773] = {
		readable = "Callum's Shield",
		model = 5740679,
		text = {
			en = "Callum's Shield",
			es = "Callum's Shield",
			mx = "Callum's Shield",
			de = "Callum's Shield",
			fr = "Callum's Shield",
			it = "Callum's Shield",
			pt = "Callum's Shield",
			ru = "Callum's Shield",
			ko = "Callum's Shield",
			cn = "Callum's Shield",
			tw = "Callum's Shield",
		},
	},
	[551815] = {
		readable = "Callum's Necklace",
		model = 4551442,
		text = {
			en = "Callum's Necklace",
			es = "Callum's Necklace",
			mx = "Callum's Necklace",
			de = "Callum's Necklace",
			fr = "Callum's Necklace",
			it = "Callum's Necklace",
			pt = "Callum's Necklace",
			ru = "Callum's Necklace",
			ko = "Callum's Necklace",
			cn = "Callum's Necklace",
			tw = "Callum's Necklace",
		},
	},
	[551817] = {
		readable = "Callum's Tinder Box",
		model = 5659419,
		text = {
			en = "Callum's Tinder Box",
			es = "Callum's Tinder Box",
			mx = "Callum's Tinder Box",
			de = "Callum's Tinder Box",
			fr = "Callum's Tinder Box",
			it = "Callum's Tinder Box",
			pt = "Callum's Tinder Box",
			ru = "Callum's Tinder Box",
			ko = "Callum's Tinder Box",
			cn = "Callum's Tinder Box",
			tw = "Callum's Tinder Box",
		},
	},
	[553793] = {
		readable = "Shield",
		model = 936452,
		text = {
			en = "Shield",
			es = "Shield",
			mx = "Shield",
			de = "Shield",
			fr = "Shield",
			it = "Shield",
			pt = "Shield",
			ru = "Shield",
			ko = "Shield",
			cn = "Shield",
			tw = "Shield",
		},
	},
	[553808] = {
		readable = "Gomphusta's Chest",
		model = 5838194,
		text = {
			en = "Gomphusta's Chest",
			es = "Gomphusta's Chest",
			mx = "Gomphusta's Chest",
			de = "Gomphusta's Chest",
			fr = "Gomphusta's Chest",
			it = "Gomphusta's Chest",
			pt = "Gomphusta's Chest",
			ru = "Gomphusta's Chest",
			ko = "Gomphusta's Chest",
			cn = "Gomphusta's Chest",
			tw = "Gomphusta's Chest",
		},
	},
	[553844] = {
		readable = "Axe",
		model = 1015733,
		text = {
			en = "Axe",
			es = "Axe",
			mx = "Axe",
			de = "Axe",
			fr = "Axe",
			it = "Axe",
			pt = "Axe",
			ru = "Axe",
			ko = "Axe",
			cn = "Axe",
			tw = "Axe",
		},
	},
	[554678] = {
		readable = "Lost Shadowstep Supplies",
		model = 5661244,
		text = {
			en = "Lost Shadowstep Supplies",
			es = "Lost Shadowstep Supplies",
			mx = "Lost Shadowstep Supplies",
			de = "Lost Shadowstep Supplies",
			fr = "Lost Shadowstep Supplies",
			it = "Lost Shadowstep Supplies",
			pt = "Lost Shadowstep Supplies",
			ru = "Lost Shadowstep Supplies",
			ko = "Lost Shadowstep Supplies",
			cn = "Lost Shadowstep Supplies",
			tw = "Lost Shadowstep Supplies",
		},
	},
	[554772] = {
		readable = "Void-Tainted Remains",
		model = 4293078,
		text = {
			en = "Void-Tainted Remains",
			es = "Void-Tainted Remains",
			mx = "Void-Tainted Remains",
			de = "Void-Tainted Remains",
			fr = "Void-Tainted Remains",
			it = "Void-Tainted Remains",
			pt = "Void-Tainted Remains",
			ru = "Void-Tainted Remains",
			ko = "Void-Tainted Remains",
			cn = "Void-Tainted Remains",
			tw = "Void-Tainted Remains",
		},
	},
	[555428] = {
		readable = "Mature Ghostflower",
		model = 6025864,
		text = {
			en = "Mature Ghostflower",
			es = "Mature Ghostflower",
			mx = "Mature Ghostflower",
			de = "Mature Ghostflower",
			fr = "Mature Ghostflower",
			it = "Mature Ghostflower",
			pt = "Mature Ghostflower",
			ru = "Mature Ghostflower",
			ko = "Mature Ghostflower",
			cn = "Mature Ghostflower",
			tw = "Mature Ghostflower",
		},
	},
	[555480] = {
		readable = "Inscribed Oar",
		model = 6195765,
		text = {
			en = "Inscribed Oar",
			es = "Inscribed Oar",
			mx = "Inscribed Oar",
			de = "Inscribed Oar",
			fr = "Inscribed Oar",
			it = "Inscribed Oar",
			pt = "Inscribed Oar",
			ru = "Inscribed Oar",
			ko = "Inscribed Oar",
			cn = "Inscribed Oar",
			tw = "Inscribed Oar",
		},
	},
})
do ObjectDB[objectID] = objectData; end
