local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[572998] = {
		readable = "Burning Branch of the World Tree",
		model = 6010159,
		text = {
			en = "Burning Branch of the World Tree",
			es = "Burning Branch of the World Tree",
			mx = "Burning Branch of the World Tree",
			de = "Burning Branch of the World Tree",
			fr = "Burning Branch of the World Tree",
			it = "Burning Branch of the World Tree",
			pt = "Burning Branch of the World Tree",
			ru = "Burning Branch of the World Tree",
			ko = "Burning Branch of the World Tree",
			cn = "Burning Branch of the World Tree",
			tw = "Burning Branch of the World Tree",
		},
	},
	[573050] = {
		readable = "Sporelord's Fight Prize",
		model = 6225715,
		text = {
			en = "Sporelord's Fight Prize",
			es = "Sporelord's Fight Prize",
			mx = "Sporelord's Fight Prize",
			de = "Sporelord's Fight Prize",
			fr = "Sporelord's Fight Prize",
			it = "Sporelord's Fight Prize",
			pt = "Sporelord's Fight Prize",
			ru = "Sporelord's Fight Prize",
			ko = "Sporelord's Fight Prize",
			cn = "Sporelord's Fight Prize",
			tw = "Sporelord's Fight Prize",
		},
	},
	[573095] = {
		readable = "Reliquary's Lost Paintbrush",
		model = 6067028,
		text = {
			en = "Reliquary's Lost Paintbrush",
			es = "Reliquary's Lost Paintbrush",
			mx = "Reliquary's Lost Paintbrush",
			de = "Reliquary's Lost Paintbrush",
			fr = "Reliquary's Lost Paintbrush",
			it = "Reliquary's Lost Paintbrush",
			pt = "Reliquary's Lost Paintbrush",
			ru = "Reliquary's Lost Paintbrush",
			ko = "Reliquary's Lost Paintbrush",
			cn = "Reliquary's Lost Paintbrush",
			tw = "Reliquary's Lost Paintbrush",
		},
	},
	[573747] = {
		readable = "Mature Blood Petal",
		model = 6210875,
		text = {
			en = "Mature Blood Petal",
			es = "Mature Blood Petal",
			mx = "Mature Blood Petal",
			de = "Mature Blood Petal",
			fr = "Mature Blood Petal",
			it = "Mature Blood Petal",
			pt = "Mature Blood Petal",
			ru = "Mature Blood Petal",
			ko = "Mature Blood Petal",
			cn = "Mature Blood Petal",
			tw = "Mature Blood Petal",
		},
	},
	[573841] = {
		readable = "Fungalcap Crock",
		model = 6225716,
		text = {
			en = "Fungalcap Crock",
			es = "Fungalcap Crock",
			mx = "Fungalcap Crock",
			de = "Fungalcap Crock",
			fr = "Fungalcap Crock",
			it = "Fungalcap Crock",
			pt = "Fungalcap Crock",
			ru = "Fungalcap Crock",
			ko = "Fungalcap Crock",
			cn = "Fungalcap Crock",
			tw = "Fungalcap Crock",
		},
	},
	[573991] = {
		readable = "Budding Barrel",
		model = 6055096,
		text = {
			en = "Budding Barrel",
			es = "Budding Barrel",
			mx = "Budding Barrel",
			de = "Budding Barrel",
			fr = "Budding Barrel",
			it = "Budding Barrel",
			pt = "Budding Barrel",
			ru = "Budding Barrel",
			ko = "Budding Barrel",
			cn = "Budding Barrel",
			tw = "Budding Barrel",
		},
	},
	[574126] = {
		readable = "Leaf-wrapped Package",
		model = 5163366,
		text = {
			en = "Leaf-wrapped Package",
			es = "Leaf-wrapped Package",
			mx = "Leaf-wrapped Package",
			de = "Leaf-wrapped Package",
			fr = "Leaf-wrapped Package",
			it = "Leaf-wrapped Package",
			pt = "Leaf-wrapped Package",
			ru = "Leaf-wrapped Package",
			ko = "Leaf-wrapped Package",
			cn = "Leaf-wrapped Package",
			tw = "Leaf-wrapped Package",
		},
	},
})
do ObjectDB[objectID] = objectData; end
