local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[423570] = {
		readable = "Pillaged Riches",
		model = 5007038,
		text = {
			en = "Pillaged Riches",
			es = "Riquezas saqueadas",
			mx = "Riquezas saqueadas",
			de = "Geplünderte Reichtümer",
			fr = "Richesses pillées",
			it = "Ricchezze Saccheggiate",
			pt = "Riquezas Saqueadas",
			ru = "Похищенные богатства",
			ko = "약탈당한 보물",
			cn = "掠夺的财富",
			tw = "掠取的財寶",
		},
	},
	[433563] = {
		readable = "Key Scroll",
		model = 5007027,
		text = {
			en = "Key Scroll",
			es = "Pergamino llave",
			mx = "Pergamino de llave",
			de = "Schlüsselschriftrolle",
			fr = "Parchemin clé",
			it = "Pergamena Chiave",
			pt = "Pergaminho-chave",
			ru = "Свиток-ключ",
			ko = "열쇠 두루마리",
			cn = "钥匙卷轴",
			tw = "鑰匙卷軸",
		},
	},
	[439466] = {
		readable = "Antiparalytic Serum",
		model = 5201694,
		text = {
			en = "Antiparalytic Serum",
			es = "Suero antiparalizante",
			mx = "Suero antiparalizante",
			de = "Lähmungsheilserum",
			fr = "Sérum antiparalytique",
			it = "Siero Antiparalisi",
			pt = "Soro Antiparalisante",
			ru = "Сыворотка для снятия паралича",
			ko = "항마비 혈청",
			cn = "抗瘫血清",
			tw = "抗麻痺藥劑",
		},
	},
	[439611] = {
		readable = "Paralytic Draught",
		model = 5201696,
		text = {
			en = "Paralytic Draught",
			es = "Jarabe paralizante",
			mx = "Jarabe paralizador",
			de = "Lähmtrunk",
			fr = "Breuvage paralysant",
			it = "Fiasca Paralizzante",
			pt = "Beberagem Paralisante",
			ru = "Парализующий настой",
			ko = "마비 비약",
			cn = "致瘫饮剂",
			tw = "麻痺藥水",
		},
	},
	[441257] = {
		readable = "Crate of Alchemical Potions",
		model = 5007037,
		text = {
			en = "Crate of Alchemical Potions",
			es = "Cajón de pociones alquímicas",
			mx = "Cajón de pociones alquímicas",
			de = "Kiste mit alchemistischen Tränken",
			fr = "Caisse de potions d’alchimie",
			it = "Cassa di Pozioni Alchemiche",
			pt = "Caixote de Poções Alquímicas",
			ru = "Ящик с алхимическими зельями",
			ko = "연금술 물약 상자",
			cn = "一箱炼金药水",
			tw = "一箱鍊金藥水",
		},
	},
	[504179] = {
		readable = "Stolen Goods",
		model = 5128194,
		text = {
			en = "Stolen Goods",
			es = "Bienes robados",
			mx = "Bienes robados",
			de = "Gestohlene Waren",
			fr = "Marchandises volées",
			it = "Merci Rubate",
			pt = "Mercadorias Roubadas",
			ru = "Украденные припасы",
			ko = "도난당한 물품",
			cn = "失窃的货物",
			tw = "被偷的貨物",
		},
	},
	[507966] = {
		readable = "Profane Research",
		model = 6025931,
		text = {
			en = "Profane Research",
			es = "Profane Research",
			mx = "Profane Research",
			de = "Profane Research",
			fr = "Profane Research",
			it = "Profane Research",
			pt = "Profane Research",
			ru = "Profane Research",
			ko = "Profane Research",
			cn = "Profane Research",
			tw = "Profane Research",
		},
	},
	[508411] = {
		readable = "Haranir Heirloom",
		model = 6055098,
		text = {
			en = "Haranir Heirloom",
			es = "Haranir Heirloom",
			mx = "Haranir Heirloom",
			de = "Haranir Heirloom",
			fr = "Haranir Heirloom",
			it = "Haranir Heirloom",
			pt = "Haranir Heirloom",
			ru = "Haranir Heirloom",
			ko = "Haranir Heirloom",
			cn = "Haranir Heirloom",
			tw = "Haranir Heirloom",
		},
	},
	[523752] = {
		readable = "Medical Supplies",
		model = 199639,
		text = {
			en = "Medical Supplies",
			es = "Medical Supplies",
			mx = "Medical Supplies",
			de = "Medical Supplies",
			fr = "Medical Supplies",
			it = "Medical Supplies",
			pt = "Medical Supplies",
			ru = "Medical Supplies",
			ko = "Medical Supplies",
			cn = "Medical Supplies",
			tw = "Medical Supplies",
		},
	},
	[526075] = {
		readable = "Torentia",
		model = 6891198,
		text = {
			en = "Torentia",
			es = "Torentia",
			mx = "Torentia",
			de = "Torentia",
			fr = "Torentia",
			it = "Torentia",
			pt = "Torentia",
			ru = "Torentia",
			ko = "Torentia",
			cn = "Torentia",
			tw = "Torentia",
		},
	},
	[526903] = {
		readable = "Memorial Plaque",
		model = 970107,
		text = {
			en = "Memorial Plaque",
			es = "Memorial Plaque",
			mx = "Memorial Plaque",
			de = "Memorial Plaque",
			fr = "Memorial Plaque",
			it = "Memorial Plaque",
			pt = "Memorial Plaque",
			ru = "Memorial Plaque",
			ko = "Memorial Plaque",
		},
	},
})
do ObjectDB[objectID] = objectData; end
