local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[649085] = {
		readable = "Brine-Crusted Chest",
		model = 6195763,
		text = {
			en = "Brine-Crusted Chest",
			es = "Brine-Crusted Chest",
			mx = "Brine-Crusted Chest",
			de = "Brine-Crusted Chest",
			fr = "Brine-Crusted Chest",
			it = "Brine-Crusted Chest",
			pt = "Brine-Crusted Chest",
			ru = "Brine-Crusted Chest",
			ko = "Brine-Crusted Chest",
			cn = "Brine-Crusted Chest",
			tw = "Brine-Crusted Chest",
		},
	},
	[649453] = {
		readable = "Ruma's Satchel",
		model = 1661561,
		text = {
			en = "Ruma's Satchel",
			es = "Ruma's Satchel",
			mx = "Ruma's Satchel",
			de = "Ruma's Satchel",
			fr = "Ruma's Satchel",
			it = "Ruma's Satchel",
			pt = "Ruma's Satchel",
			ru = "Ruma's Satchel",
			ko = "Ruma's Satchel",
			cn = "Ruma's Satchel",
			tw = "Ruma's Satchel",
		},
	},
	[649481] = {
		readable = "Wood Debris",
		model = 4329937,
		text = {
			en = "Wood Debris",
			es = "Wood Debris",
			mx = "Wood Debris",
			de = "Wood Debris",
			fr = "Wood Debris",
			it = "Wood Debris",
			pt = "Wood Debris",
			ru = "Wood Debris",
			ko = "Wood Debris",
			cn = "Wood Debris",
			tw = "Wood Debris",
		},
	},
	[649640] = {
		readable = "Soulcoiler's Cache",
		text = {
			en = "Soulcoiler's Cache",
			es = "Soulcoiler's Cache",
			mx = "Soulcoiler's Cache",
			de = "Soulcoiler's Cache",
			fr = "Soulcoiler's Cache",
			it = "Soulcoiler's Cache",
			pt = "Soulcoiler's Cache",
			ru = "Soulcoiler's Cache",
			ko = "Soulcoiler's Cache",
			cn = "Soulcoiler's Cache",
			tw = "Soulcoiler's Cache",
		},
	},
	[653176] = {
		readable = "Unguarded Chest",
		model = 1315888,
		text = {
			en = "Unguarded Chest",
			es = "Unguarded Chest",
			mx = "Unguarded Chest",
			de = "Unguarded Chest",
			fr = "Unguarded Chest",
			it = "Unguarded Chest",
			pt = "Unguarded Chest",
			ru = "Unguarded Chest",
			ko = "Unguarded Chest",
			cn = "Unguarded Chest",
			tw = "Unguarded Chest",
		},
	},
	[653374] = {
		readable = "A Message from Kul'amara",
		model = 5975119,
		text = {
			en = "A Message from Kul'amara",
			es = "A Message from Kul'amara",
			mx = "A Message from Kul'amara",
			de = "A Message from Kul'amara",
			fr = "A Message from Kul'amara",
			it = "A Message from Kul'amara",
			pt = "A Message from Kul'amara",
			ru = "A Message from Kul'amara",
			ko = "A Message from Kul'amara",
			cn = "A Message from Kul'amara",
			tw = "A Message from Kul'amara",
		},
	},
	[653515] = {
		readable = "Head Mason's Tablet",
		model = 6212409,
		text = {
			en = "Head Mason's Tablet",
			es = "Head Mason's Tablet",
			mx = "Head Mason's Tablet",
			de = "Head Mason's Tablet",
			fr = "Head Mason's Tablet",
			it = "Head Mason's Tablet",
			pt = "Head Mason's Tablet",
			ru = "Head Mason's Tablet",
			ko = "Head Mason's Tablet",
			cn = "Head Mason's Tablet",
			tw = "Head Mason's Tablet",
		},
	},
	[653579] = {
		readable = "Amani Exile's Words",
		text = {
			en = "Amani Exile's Words",
			es = "Amani Exile's Words",
			mx = "Amani Exile's Words",
			de = "Amani Exile's Words",
			fr = "Amani Exile's Words",
			it = "Amani Exile's Words",
			pt = "Amani Exile's Words",
			ru = "Amani Exile's Words",
			ko = "Amani Exile's Words",
			cn = "Amani Exile's Words",
			tw = "Amani Exile's Words",
		},
	},
	[654586] = {
		readable = "Worn Tablet",
		model = 6212412,
		text = {
			en = "Worn Tablet",
			es = "Worn Tablet",
			mx = "Worn Tablet",
			de = "Worn Tablet",
			fr = "Worn Tablet",
			it = "Worn Tablet",
			pt = "Worn Tablet",
			ru = "Worn Tablet",
			ko = "Worn Tablet",
			cn = "Worn Tablet",
			tw = "Worn Tablet",
		},
	},
})
do ObjectDB[objectID] = objectData; end
