local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[587264] = {
		readable = "Golden Cloud Serpent Treasure Chest",
		model = 629723,
		text = {
			en = "Golden Cloud Serpent Treasure Chest",
			es = "[Golden Cloud Serpent Treasure Chest]",
			mx = "[Golden Cloud Serpent Treasure Chest]",
			de = "Goldwolkenschlangen-Schatztruhe",
			fr = "Coffre au trésor du serpent-nuage doré",
			it = "[Golden Cloud Serpent Treasure Chest]",
			pt = "[Golden Cloud Serpent Treasure Chest]",
			ru = "Сундук с сокровищами золотистого облачного змея",
			ko = "황금빛 운룡 보물 상자",
			cn = "[Golden Cloud Serpent Treasure Chest]",
			tw = "金色雲蛟寶箱",
		},
	},
	[588832] = {
		readable = "Fallen Hunter",
		model = 6366141,
		text = {
			en = "Fallen Hunter",
			es = "Fallen Hunter",
			mx = "Fallen Hunter",
			de = "Fallen Hunter",
			fr = "Fallen Hunter",
			it = "Fallen Hunter",
			pt = "Fallen Hunter",
			ru = "Fallen Hunter",
			ko = "Fallen Hunter",
			cn = "Fallen Hunter",
			tw = "Fallen Hunter",
		},
	},
	[588966] = {
		readable = "A Tattered Ball",
		model = 969722,
		text = {
			en = "A Tattered Ball",
			es = "A Tattered Ball",
			mx = "A Tattered Ball",
			de = "A Tattered Ball",
			fr = "A Tattered Ball",
			it = "A Tattered Ball",
			pt = "A Tattered Ball",
			ru = "A Tattered Ball",
			ko = "A Tattered Ball",
			cn = "A Tattered Ball",
			tw = "A Tattered Ball",
		},
	},
	[602759] = {
		readable = "Ka'dani Spear",
		model = 6252866,
		text = {
			en = "Ka'dani Spear",
			es = "Ka'dani Spear",
			mx = "Ka'dani Spear",
			de = "Ka'dani Spear",
			fr = "Ka'dani Spear",
			it = "Ka'dani Spear",
			pt = "Ka'dani Spear",
			ru = "Ka'dani Spear",
			ko = "Ka'dani Spear",
			cn = "Ka'dani Spear",
			tw = "Ka'dani Spear",
		},
	},
	[609910] = {
		readable = "Depleted Void Canister",
		model = 6391988,
		text = {
			en = "Depleted Void Canister",
			es = "Depleted Void Canister",
			mx = "Depleted Void Canister",
			de = "Depleted Void Canister",
			fr = "Depleted Void Canister",
			it = "Depleted Void Canister",
			pt = "Depleted Void Canister",
			ru = "Depleted Void Canister",
			ko = "Depleted Void Canister",
			cn = "Depleted Void Canister",
			tw = "Depleted Void Canister",
		},
	},
	[611933] = {
		readable = "The Shadow Enclave",
		model = 6103389,
		text = {
			en = "The Shadow Enclave",
			es = "The Shadow Enclave",
			mx = "The Shadow Enclave",
			de = "The Shadow Enclave",
			fr = "The Shadow Enclave",
			it = "The Shadow Enclave",
			pt = "The Shadow Enclave",
			ru = "The Shadow Enclave",
			ko = "The Shadow Enclave",
			cn = "The Shadow Enclave",
			tw = "The Shadow Enclave",
		},
	},
	[612039] = {
		readable = "The Darkway",
		model = 1367309,
		text = {
			en = "The Darkway",
			es = "The Darkway",
			mx = "The Darkway",
			de = "The Darkway",
			fr = "The Darkway",
			it = "The Darkway",
			pt = "The Darkway",
			ru = "The Darkway",
			ko = "The Darkway",
			cn = "The Darkway",
			tw = "The Darkway",
		},
	},
	[612242] = {
		readable = "Twilight Crypts",
		model = 936419,
		text = {
			en = "Twilight Crypts",
			es = "Twilight Crypts",
			mx = "Twilight Crypts",
			de = "Twilight Crypts",
			fr = "Twilight Crypts",
			it = "Twilight Crypts",
			pt = "Twilight Crypts",
		},
	},
})
do ObjectDB[objectID] = objectData; end
