local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[584504] = {
		readable = "<span style=\"color: #0070dd\">Sanctified Spoils</span>",
		model = 6435027,
		text = {
			en = "<span style=\"color: #0070dd\">Sanctified Spoils</span>",
			es = "<span style=\"color: #0070dd\">Sanctified Spoils</span>",
			mx = "<span style=\"color: #0070dd\">Sanctified Spoils</span>",
			de = "<span style=\"color: #0070dd\">Sanctified Spoils</span>",
			fr = "<span style=\"color: #0070dd\">Sanctified Spoils</span>",
			it = "<span style=\"color: #0070dd\">Sanctified Spoils</span>",
			pt = "<span style=\"color: #0070dd\">Sanctified Spoils</span>",
			ru = "<span style=\"color: #0070dd\">Sanctified Spoils</span>",
			ko = "<span style=\"color: #0070dd\">Sanctified Spoils</span>",
			cn = "<span style=\"color: #0070dd\">Sanctified Spoils</span>",
			tw = "<span style=\"color: #0070dd\">Sanctified Spoils</span>",
		},
	},
	[584508] = {
		readable = "<span style=\"color: #A335EE\">Nemesis Strongbox</span>",
		model = 2907352,
		text = {
			en = "<span style=\"color: #A335EE\">Nemesis Strongbox</span>",
			es = "<span style=\"color: #A335EE\">Nemesis Strongbox</span>",
			mx = "<span style=\"color: #A335EE\">Nemesis Strongbox</span>",
			de = "<span style=\"color: #A335EE\">Nemesis Strongbox</span>",
			fr = "<span style=\"color: #A335EE\">Nemesis Strongbox</span>",
			it = "<span style=\"color: #A335EE\">Nemesis Strongbox</span>",
			pt = "<span style=\"color: #A335EE\">Nemesis Strongbox</span>",
			ru = "<span style=\"color: #A335EE\">Nemesis Strongbox</span>",
			ko = "<span style=\"color: #A335EE\">Nemesis Strongbox</span>",
			cn = "<span style=\"color: #A335EE\">Nemesis Strongbox</span>",
			tw = "<span style=\"color: #A335EE\">Nemesis Strongbox</span>",
		},
	},
	[584509] = {
		readable = "<span style=\"color: #0070dd\">Nemesis Strongbox</span>",
		model = 2907352,
		text = {
			en = "<span style=\"color: #0070dd\">Nemesis Strongbox</span>",
			es = "<span style=\"color: #0070dd\">Nemesis Strongbox</span>",
			mx = "<span style=\"color: #0070dd\">Nemesis Strongbox</span>",
			de = "<span style=\"color: #0070dd\">Nemesis Strongbox</span>",
			fr = "<span style=\"color: #0070dd\">Nemesis Strongbox</span>",
			it = "<span style=\"color: #0070dd\">Nemesis Strongbox</span>",
			pt = "<span style=\"color: #0070dd\">Nemesis Strongbox</span>",
			ru = "<span style=\"color: #0070dd\">Nemesis Strongbox</span>",
			ko = "<span style=\"color: #0070dd\">Nemesis Strongbox</span>",
			cn = "<span style=\"color: #0070dd\">Nemesis Strongbox</span>",
			tw = "<span style=\"color: #0070dd\">Nemesis Strongbox</span>",
		},
	},
	[584511] = {
		readable = "<span style=\"color: #1EFF00\">Nemesis Strongbox</span>",
		model = 2907352,
		text = {
			en = "<span style=\"color: #1EFF00\">Nemesis Strongbox</span>",
			es = "<span style=\"color: #1EFF00\">Nemesis Strongbox</span>",
			mx = "<span style=\"color: #1EFF00\">Nemesis Strongbox</span>",
			de = "<span style=\"color: #1EFF00\">Nemesis Strongbox</span>",
			fr = "<span style=\"color: #1EFF00\">Nemesis Strongbox</span>",
			it = "<span style=\"color: #1EFF00\">Nemesis Strongbox</span>",
			pt = "<span style=\"color: #1EFF00\">Nemesis Strongbox</span>",
			ru = "<span style=\"color: #1EFF00\">Nemesis Strongbox</span>",
			ko = "<span style=\"color: #1EFF00\">Nemesis Strongbox</span>",
			cn = "<span style=\"color: #1EFF00\">Nemesis Strongbox</span>",
			tw = "<span style=\"color: #1EFF00\">Nemesis Strongbox</span>",
		},
	},
	[584514] = {
		readable = "<span style=\"color: #A335EE\">Bountiful Coffer</span>",
		model = 5869301,
		text = {
			en = "<span style=\"color: #A335EE\">Bountiful Coffer</span>",
			es = "<span style=\"color: #A335EE\">Bountiful Coffer</span>",
			mx = "<span style=\"color: #A335EE\">Bountiful Coffer</span>",
			de = "<span style=\"color: #A335EE\">Bountiful Coffer</span>",
			fr = "<span style=\"color: #A335EE\">Bountiful Coffer</span>",
			it = "<span style=\"color: #A335EE\">Bountiful Coffer</span>",
			pt = "<span style=\"color: #A335EE\">Bountiful Coffer</span>",
			ru = "<span style=\"color: #A335EE\">Bountiful Coffer</span>",
			ko = "<span style=\"color: #A335EE\">Bountiful Coffer</span>",
			cn = "<span style=\"color: #A335EE\">Bountiful Coffer</span>",
			tw = "<span style=\"color: #A335EE\">Bountiful Coffer</span>",
		},
	},
	[584525] = {
		readable = "Sporeglider's Tail Spore",
		model = 6225696,
		text = {
			en = "Sporeglider's Tail Spore",
			es = "Sporeglider's Tail Spore",
			mx = "Sporeglider's Tail Spore",
			de = "Sporeglider's Tail Spore",
			fr = "Sporeglider's Tail Spore",
			it = "Sporeglider's Tail Spore",
			pt = "Sporeglider's Tail Spore",
			ru = "Sporeglider's Tail Spore",
			ko = "Sporeglider's Tail Spore",
			cn = "Sporeglider's Tail Spore",
			tw = "Sporeglider's Tail Spore",
		},
	},
	[584752] = {
		readable = "Mislaid Curiosity",
		model = 5100456,
		text = {
			en = "Mislaid Curiosity",
			es = "Mislaid Curiosity",
			mx = "Mislaid Curiosity",
			de = "Mislaid Curiosity",
			fr = "Mislaid Curiosity",
			it = "Mislaid Curiosity",
			pt = "Mislaid Curiosity",
			ru = "Mislaid Curiosity",
			ko = "Mislaid Curiosity",
			cn = "Mislaid Curiosity",
		},
	},
})
do ObjectDB[objectID] = objectData; end
