local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[527509] = {
		readable = "Greater Alndust",
		model = 3195530,
		text = {
			en = "Greater Alndust",
			es = "Greater Alndust",
			mx = "Greater Alndust",
			de = "Greater Alndust",
			fr = "Greater Alndust",
			it = "Greater Alndust",
			pt = "Greater Alndust",
			ru = "Greater Alndust",
			ko = "Greater Alndust",
			cn = "Greater Alndust",
			tw = "Greater Alndust",
		},
	},
	[528034] = {
		readable = "Fallen Branch",
		model = 3888309,
		text = {
			en = "Fallen Branch",
			es = "Fallen Branch",
			mx = "Fallen Branch",
			de = "Fallen Branch",
			fr = "Fallen Branch",
			it = "Fallen Branch",
			pt = "Fallen Branch",
			ru = "Fallen Branch",
			ko = "Fallen Branch",
			cn = "Fallen Branch",
			tw = "Fallen Branch",
		},
	},
	[528071] = {
		readable = "Shrine Piece",
		model = 6388967,
		text = {
			en = "Shrine Piece",
			es = "Shrine Piece",
			mx = "Shrine Piece",
			de = "Shrine Piece",
			fr = "Shrine Piece",
			it = "Shrine Piece",
			pt = "Shrine Piece",
			ru = "Shrine Piece",
			ko = "Shrine Piece",
			cn = "Shrine Piece",
			tw = "Shrine Piece",
		},
	},
	[529370] = {
		readable = "Stray Skyshards",
		model = 1306217,
		text = {
			en = "Stray Skyshards",
			es = "Stray Skyshards",
			mx = "Stray Skyshards",
			de = "Stray Skyshards",
			fr = "Stray Skyshards",
			it = "Stray Skyshards",
			pt = "Stray Skyshards",
			ru = "Stray Skyshards",
			ko = "Stray Skyshards",
			cn = "Stray Skyshards",
			tw = "Stray Skyshards",
		},
	},
	[529725] = {
		readable = "Hieron's Journal",
		model = 5975116,
		text = {
			en = "Hieron's Journal",
			es = "Hieron's Journal",
			mx = "Hieron's Journal",
			de = "Hieron's Journal",
			fr = "Hieron's Journal",
			it = "Hieron's Journal",
			pt = "Hieron's Journal",
			ru = "Hieron's Journal",
			ko = "Hieron's Journal",
			cn = "Hieron's Journal",
			tw = "Hieron's Journal",
		},
	},
	[531213] = {
		readable = "Old Amani Pot",
		model = 6212426,
		text = {
			en = "Old Amani Pot",
			es = "Old Amani Pot",
			mx = "Old Amani Pot",
			de = "Old Amani Pot",
			fr = "Old Amani Pot",
			it = "Old Amani Pot",
			pt = "Old Amani Pot",
			ru = "Old Amani Pot",
			ko = "Old Amani Pot",
			cn = "Old Amani Pot",
			tw = "Old Amani Pot",
		},
	},
	[531495] = {
		readable = "Slain Beast",
		model = 124640,
		text = {
			en = "Slain Beast",
			es = "Slain Beast",
			mx = "Slain Beast",
			de = "Slain Beast",
			fr = "Slain Beast",
			it = "Slain Beast",
			pt = "Slain Beast",
			ru = "Slain Beast",
			ko = "Slain Beast",
			cn = "Slain Beast",
			tw = "Slain Beast",
		},
	},
	[532226] = {
		readable = "The Catalyst",
		model = 6648659,
		text = {
			en = "The Catalyst",
			es = "The Catalyst",
			mx = "The Catalyst",
			de = "The Catalyst",
			fr = "The Catalyst",
			it = "The Catalyst",
			pt = "The Catalyst",
			ru = "The Catalyst",
			ko = "The Catalyst",
			cn = "The Catalyst",
			tw = "The Catalyst",
		},
	},
	[539047] = {
		readable = "Abandoned Ritual Skull",
		model = 6153816,
		text = {
			en = "Abandoned Ritual Skull",
			es = "Abandoned Ritual Skull",
			mx = "Abandoned Ritual Skull",
			de = "Abandoned Ritual Skull",
			fr = "Abandoned Ritual Skull",
			it = "Abandoned Ritual Skull",
			pt = "Abandoned Ritual Skull",
			ru = "Abandoned Ritual Skull",
			ko = "Abandoned Ritual Skull",
			cn = "Abandoned Ritual Skull",
			tw = "Abandoned Ritual Skull",
		},
	},
	[539208] = {
		readable = "Healing Waters of Ahl'ua",
		model = 4290532,
		text = {
			en = "Healing Waters of Ahl'ua",
			es = "Healing Waters of Ahl'ua",
			mx = "Healing Waters of Ahl'ua",
			de = "Healing Waters of Ahl'ua",
			fr = "Healing Waters of Ahl'ua",
			it = "Healing Waters of Ahl'ua",
			pt = "Healing Waters of Ahl'ua",
			ru = "Healing Waters of Ahl'ua",
			ko = "Healing Waters of Ahl'ua",
			cn = "Healing Waters of Ahl'ua",
			tw = "Healing Waters of Ahl'ua",
		},
	},
})
do ObjectDB[objectID] = objectData; end
