local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[669314] = {
		readable = "Zandalari Logbook",
		text = {
			en = "Zandalari Logbook",
			es = "Zandalari Logbook",
			mx = "Zandalari Logbook",
			de = "Zandalari Logbook",
			fr = "Zandalari Logbook",
			it = "Zandalari Logbook",
			pt = "Zandalari Logbook",
			ru = "Zandalari Logbook",
			ko = "Zandalari Logbook",
			cn = "Zandalari Logbook",
			tw = "Zandalari Logbook",
		},
	},
	[669316] = {
		readable = "Oily Black Stone",
		model = 3008934,
		text = {
			en = "Oily Black Stone",
			es = "Oily Black Stone",
			mx = "Oily Black Stone",
			de = "Oily Black Stone",
			fr = "Oily Black Stone",
			it = "Oily Black Stone",
			pt = "Oily Black Stone",
			ru = "Oily Black Stone",
			ko = "Oily Black Stone",
			cn = "Oily Black Stone",
			tw = "Oily Black Stone",
		},
	},
	[669317] = {
		readable = "Forum Rules",
		model = 6212409,
		text = {
			en = "Forum Rules",
			es = "Forum Rules",
			mx = "Forum Rules",
			de = "Forum Rules",
			fr = "Forum Rules",
			it = "Forum Rules",
			pt = "Forum Rules",
			ru = "Forum Rules",
			ko = "Forum Rules",
			cn = "Forum Rules",
			tw = "Forum Rules",
		},
	},
	[669318] = {
		readable = "Survival Journals",
		model = 2026831,
		text = {
			en = "Survival Journals",
			es = "Survival Journals",
			mx = "Survival Journals",
			de = "Survival Journals",
			fr = "Survival Journals",
			it = "Survival Journals",
			pt = "Survival Journals",
			ru = "Survival Journals",
			ko = "Survival Journals",
			cn = "Survival Journals",
			tw = "Survival Journals",
		},
	},
	[669320] = {
		readable = "Profaned Plaque",
		text = {
			en = "Profaned Plaque",
			es = "Profaned Plaque",
			mx = "Profaned Plaque",
			de = "Profaned Plaque",
			fr = "Profaned Plaque",
			it = "Profaned Plaque",
			pt = "Profaned Plaque",
			ru = "Profaned Plaque",
			ko = "Profaned Plaque",
			cn = "Profaned Plaque",
			tw = "Profaned Plaque",
		},
	},
})
do ObjectDB[objectID] = objectData; end
