local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[508350] = {
		readable = "Portal to Stormwind",
		model = 3613783,
		text = {
			en = "Portal to Stormwind",
			es = "Portal a Ventormenta",
			mx = "Portal a Ventormenta",
			de = "Portal nach Sturmwind",
			fr = "Portail vers Hurlevent",
			it = "Portale per Roccavento",
			pt = "Portal para Ventobravo",
			ru = "Портал в Штормград",
			ko = "스톰윈드로 통하는 차원문",
			cn = "通往暴风城的传送门",
			tw = "暴風城傳送門",
		},
	},
	[553558] = {
		readable = "Cultist Dagger",
		model = 5975138,
		text = {
			en = "Cultist Dagger",
			es = "Daga de cultor",
			mx = "Daga de cultor",
			de = "Kultistendolch",
			fr = "Dague de sectateur",
			it = "Pugnale da Cultista",
			pt = "Adaga de Sectário",
			ru = "Кинжал сектанта",
			ko = "이교도 단검",
			cn = "教徒匕首",
			tw = "[Cultist Dagger]",
		},
	},
	[564560] = {
		readable = "Aln'hara's Bloom",
		model = 6252875,
		text = {
			en = "Aln'hara's Bloom",
			es = "Aln'hara's Bloom",
			mx = "Aln'hara's Bloom",
			de = "Aln'hara's Bloom",
			fr = "Aln'hara's Bloom",
			it = "Aln'hara's Bloom",
			pt = "Aln'hara's Bloom",
			ru = "Aln'hara's Bloom",
			ko = "Aln'hara's Bloom",
			cn = "Aln'hara's Bloom",
			tw = "Aln'hara's Bloom",
		},
	},
	[566765] = {
		readable = "Stolen Twilight's Blade Stratagem",
		model = 6005303,
		text = {
			en = "Stolen Twilight's Blade Stratagem",
			es = "Estratagema de la Hoja Crepuscular robada",
			mx = "Estratagema de la Daga Crepuscular robada",
			de = "Gestohlenes Strategem der Zwielichtklinge",
			fr = "Stratagème de la Lame du Crépuscule volée",
			it = "Stratagemma della Lama del Crepuscolo Trafugato",
			pt = "Estratagema Roubado da Lâmina Crepuscular",
			ru = "Украденная стратагема Сумеречного Клинка",
			ko = "도둑맞은 황혼의 칼날단 전략",
			cn = "被盗的暮光之刃战略",
			tw = "遭竊的暮光之刃計謀",
		},
	},
	[570882] = {
		readable = "Inert Shadow Crystal",
		model = 6856618,
		text = {
			en = "Inert Shadow Crystal",
			es = "Cristal de las Sombras inerte",
			mx = "Cristal de sombras inerte",
			de = "Inaktiver Schattenkristall",
			fr = "Cristal ombreux inerte",
			it = "Cristallo d'Ombra Inerte",
			pt = "Cristal Sombrio Inerte",
			ru = "Угасший сумрачный кристалл",
			ko = "마력을 잃은 암흑 수정",
			cn = "惰性暗影水晶",
			tw = "[Inert Shadow Crystal]",
		},
	},
	[571142] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571143] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571144] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571145] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
		},
	},
})
do ObjectDB[objectID] = objectData; end
