local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[571162] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571165] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571173] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571175] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571282] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[572035] = {
		readable = "Weathered Tome",
		model = 985164,
		text = {
			en = "Weathered Tome",
			es = "Weathered Tome",
			mx = "Weathered Tome",
			de = "Weathered Tome",
			fr = "Weathered Tome",
			it = "Weathered Tome",
			pt = "Weathered Tome",
			ru = "Weathered Tome",
			ko = "Weathered Tome",
			cn = "Weathered Tome",
			tw = "Weathered Tome",
		},
	},
	[572428] = {
		readable = "Lost Amani Bolt",
		model = 6195762,
		text = {
			en = "Lost Amani Bolt",
			es = "Lost Amani Bolt",
			mx = "Lost Amani Bolt",
			de = "Lost Amani Bolt",
			fr = "Lost Amani Bolt",
			it = "Lost Amani Bolt",
			pt = "Lost Amani Bolt",
			ru = "Lost Amani Bolt",
			ko = "Lost Amani Bolt",
			cn = "Lost Amani Bolt",
			tw = "Lost Amani Bolt",
		},
	},
	[572958] = {
		readable = "Failed Shroom Jumper's Satchel",
		model = 6225691,
		text = {
			en = "Failed Shroom Jumper's Satchel",
			es = "Failed Shroom Jumper's Satchel",
			mx = "Failed Shroom Jumper's Satchel",
		},
	},
})
do ObjectDB[objectID] = objectData; end
