local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[668596] = {
		readable = "Funerary Inscription",
		model = 6212412,
		text = {
			en = "Funerary Inscription",
			es = "Funerary Inscription",
			mx = "Funerary Inscription",
			de = "Funerary Inscription",
			fr = "Funerary Inscription",
			it = "Funerary Inscription",
			pt = "Funerary Inscription",
			ru = "Funerary Inscription",
			ko = "Funerary Inscription",
			cn = "Funerary Inscription",
			tw = "Funerary Inscription",
		},
	},
	[668597] = {
		readable = "Funerary Inscription",
		model = 6212412,
		text = {
			en = "Funerary Inscription",
			es = "Funerary Inscription",
			mx = "Funerary Inscription",
			de = "Funerary Inscription",
			fr = "Funerary Inscription",
			it = "Funerary Inscription",
			pt = "Funerary Inscription",
			ru = "Funerary Inscription",
			ko = "Funerary Inscription",
			cn = "Funerary Inscription",
			tw = "Funerary Inscription",
		},
	},
	[668598] = {
		readable = "Funerary Inscription",
		model = 6212412,
		text = {
			en = "Funerary Inscription",
			es = "Funerary Inscription",
			mx = "Funerary Inscription",
			de = "Funerary Inscription",
			fr = "Funerary Inscription",
			it = "Funerary Inscription",
			pt = "Funerary Inscription",
			ru = "Funerary Inscription",
			ko = "Funerary Inscription",
			cn = "Funerary Inscription",
			tw = "Funerary Inscription",
		},
	},
	[668599] = {
		readable = "Funerary Inscription",
		model = 6212412,
		text = {
			en = "Funerary Inscription",
			es = "Funerary Inscription",
			mx = "Funerary Inscription",
			de = "Funerary Inscription",
			fr = "Funerary Inscription",
			it = "Funerary Inscription",
			pt = "Funerary Inscription",
			ru = "Funerary Inscription",
			ko = "Funerary Inscription",
			cn = "Funerary Inscription",
			tw = "Funerary Inscription",
		},
	},
	[668600] = {
		readable = "Funerary Inscription",
		model = 6212412,
		text = {
			en = "Funerary Inscription",
			es = "Funerary Inscription",
			mx = "Funerary Inscription",
			de = "Funerary Inscription",
			fr = "Funerary Inscription",
			it = "Funerary Inscription",
			pt = "Funerary Inscription",
			ru = "Funerary Inscription",
			ko = "Funerary Inscription",
			cn = "Funerary Inscription",
			tw = "Funerary Inscription",
		},
	},
	[668601] = {
		readable = "Funerary Inscription",
		model = 6212412,
		text = {
			en = "Funerary Inscription",
			es = "Funerary Inscription",
			mx = "Funerary Inscription",
			de = "Funerary Inscription",
			fr = "Funerary Inscription",
			it = "Funerary Inscription",
			pt = "Funerary Inscription",
			ru = "Funerary Inscription",
			ko = "Funerary Inscription",
			cn = "Funerary Inscription",
			tw = "Funerary Inscription",
		},
	},
	[668602] = {
		readable = "Funerary Inscription",
		model = 6212412,
		text = {
			en = "Funerary Inscription",
			es = "Funerary Inscription",
			mx = "Funerary Inscription",
			de = "Funerary Inscription",
			fr = "Funerary Inscription",
			it = "Funerary Inscription",
			pt = "Funerary Inscription",
			ru = "Funerary Inscription",
			ko = "Funerary Inscription",
			cn = "Funerary Inscription",
			tw = "Funerary Inscription",
		},
	},
	[669308] = {
		readable = "Abandoned Tablet",
		model = 6212409,
		text = {
			en = "Abandoned Tablet",
			es = "Abandoned Tablet",
			mx = "Abandoned Tablet",
			de = "Abandoned Tablet",
			fr = "Abandoned Tablet",
			it = "Abandoned Tablet",
			pt = "Abandoned Tablet",
			ru = "Abandoned Tablet",
			ko = "Abandoned Tablet",
			cn = "Abandoned Tablet",
			tw = "Abandoned Tablet",
		},
	},
	[669312] = {
		readable = "Message in a Bottle",
		model = 1634604,
		text = {
			en = "Message in a Bottle",
			es = "Message in a Bottle",
			mx = "Message in a Bottle",
			de = "Message in a Bottle",
			fr = "Message in a Bottle",
			it = "Message in a Bottle",
			pt = "Message in a Bottle",
			ru = "Message in a Bottle",
			ko = "Message in a Bottle",
			cn = "Message in a Bottle",
			tw = "Message in a Bottle",
		},
	},
})
do ObjectDB[objectID] = objectData; end
