local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[574619] = {
		readable = "Rich Loamy Soil",
		model = 189528,
		text = {
			en = "Rich Loamy Soil",
			es = "Rich Loamy Soil",
			mx = "Rich Loamy Soil",
			de = "Rich Loamy Soil",
			fr = "Rich Loamy Soil",
			it = "Rich Loamy Soil",
			pt = "Rich Loamy Soil",
			ru = "Rich Loamy Soil",
			ko = "Rich Loamy Soil",
			cn = "Rich Loamy Soil",
			tw = "Rich Loamy Soil",
		},
	},
	[574830] = {
		readable = "Heartwisp Shrub",
		model = 5770081,
		text = {
			en = "Heartwisp Shrub",
			es = "Heartwisp Shrub",
			mx = "Heartwisp Shrub",
			de = "Heartwisp Shrub",
			fr = "Heartwisp Shrub",
			it = "Heartwisp Shrub",
			pt = "Heartwisp Shrub",
			ru = "Heartwisp Shrub",
			ko = "Heartwisp Shrub",
			cn = "Heartwisp Shrub",
			tw = "Heartwisp Shrub",
		},
	},
	[579123] = {
		readable = "Words of Obayo--Part 1: The Flame",
		model = 6326920,
		text = {
			en = "Words of Obayo--Part 1: The Flame",
			es = "Words of Obayo--Part 1: The Flame",
			mx = "Words of Obayo--Part 1: The Flame",
			de = "Words of Obayo--Part 1: The Flame",
			fr = "Words of Obayo--Part 1: The Flame",
			it = "Words of Obayo--Part 1: The Flame",
			pt = "Words of Obayo--Part 1: The Flame",
			ru = "Words of Obayo--Part 1: The Flame",
			ko = "Words of Obayo--Part 1: The Flame",
			cn = "Words of Obayo--Part 1: The Flame",
			tw = "Words of Obayo--Part 1: The Flame",
		},
	},
	[579130] = {
		readable = "Words of Obayo--Part 2: The Rift",
		model = 6326920,
		text = {
			en = "Words of Obayo--Part 2: The Rift",
			es = "Words of Obayo--Part 2: The Rift",
			mx = "Words of Obayo--Part 2: The Rift",
			de = "Words of Obayo--Part 2: The Rift",
			fr = "Words of Obayo--Part 2: The Rift",
			it = "Words of Obayo--Part 2: The Rift",
			pt = "Words of Obayo--Part 2: The Rift",
			ru = "Words of Obayo--Part 2: The Rift",
			ko = "Words of Obayo--Part 2: The Rift",
			cn = "Words of Obayo--Part 2: The Rift",
			tw = "Words of Obayo--Part 2: The Rift",
		},
	},
	[579131] = {
		readable = "Words of Obayo--Part 3: The Silence",
		model = 6326920,
		text = {
			en = "Words of Obayo--Part 3: The Silence",
			es = "Words of Obayo--Part 3: The Silence",
			mx = "Words of Obayo--Part 3: The Silence",
			de = "Words of Obayo--Part 3: The Silence",
			fr = "Words of Obayo--Part 3: The Silence",
			it = "Words of Obayo--Part 3: The Silence",
			pt = "Words of Obayo--Part 3: The Silence",
			ru = "Words of Obayo--Part 3: The Silence",
			ko = "Words of Obayo--Part 3: The Silence",
			cn = "Words of Obayo--Part 3: The Silence",
			tw = "Words of Obayo--Part 3: The Silence",
		},
	},
	[579236] = {
		readable = "Echoes of Our Past--Part 1: Fading History",
		model = 6326920,
		text = {
			en = "Echoes of Our Past--Part 1: Fading History",
			es = "Echoes of Our Past--Part 1: Fading History",
			mx = "Echoes of Our Past--Part 1: Fading History",
			de = "Echoes of Our Past--Part 1: Fading History",
			fr = "Echoes of Our Past--Part 1: Fading History",
			it = "Echoes of Our Past--Part 1: Fading History",
		},
	},
})
do ObjectDB[objectID] = objectData; end
