local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[612259] = {
		readable = "The Gulf of Memory",
		model = 6326917,
		text = {
			en = "The Gulf of Memory",
			es = "The Gulf of Memory",
			mx = "The Gulf of Memory",
			de = "The Gulf of Memory",
			fr = "The Gulf of Memory",
			it = "The Gulf of Memory",
			pt = "The Gulf of Memory",
			ru = "The Gulf of Memory",
			ko = "The Gulf of Memory",
			cn = "The Gulf of Memory",
			tw = "The Gulf of Memory",
		},
	},
	[612264] = {
		readable = "The Grudge Pit",
		model = 6326917,
		text = {
			en = "The Grudge Pit",
			es = "The Grudge Pit",
			mx = "The Grudge Pit",
			de = "The Grudge Pit",
			fr = "The Grudge Pit",
			it = "The Grudge Pit",
			pt = "The Grudge Pit",
			ru = "The Grudge Pit",
			ko = "The Grudge Pit",
			cn = "The Grudge Pit",
			tw = "The Grudge Pit",
		},
	},
	[612354] = {
		readable = "Sunkiller Sanctum",
		model = 6320139,
		text = {
			en = "Sunkiller Sanctum",
			es = "Sunkiller Sanctum",
			mx = "Sunkiller Sanctum",
			de = "Sunkiller Sanctum",
			fr = "Sunkiller Sanctum",
			it = "Sunkiller Sanctum",
			pt = "Sunkiller Sanctum",
			ru = "Sunkiller Sanctum",
			ko = "Sunkiller Sanctum",
			cn = "Sunkiller Sanctum",
			tw = "Sunkiller Sanctum",
		},
	},
	[612364] = {
		readable = "Shadowguard Point",
		model = 6320139,
		text = {
			en = "Shadowguard Point",
			es = "Shadowguard Point",
			mx = "Shadowguard Point",
			de = "Shadowguard Point",
			fr = "Shadowguard Point",
			it = "Shadowguard Point",
			pt = "Shadowguard Point",
			ru = "Shadowguard Point",
			ko = "Shadowguard Point",
			cn = "Shadowguard Point",
			tw = "Shadowguard Point",
		},
	},
	[612894] = {
		readable = "Parhelion Plaza",
		model = 6103389,
		text = {
			en = "Parhelion Plaza",
			es = "Parhelion Plaza",
			mx = "Parhelion Plaza",
			de = "Parhelion Plaza",
			fr = "Parhelion Plaza",
			it = "Parhelion Plaza",
			pt = "Parhelion Plaza",
			ru = "Parhelion Plaza",
			ko = "Parhelion Plaza",
			cn = "Parhelion Plaza",
			tw = "Parhelion Plaza",
		},
	},
	[613242] = {
		readable = "Antique Nobleman's Signet Ring",
		model = 6210863,
		text = {
			en = "Antique Nobleman's Signet Ring",
			es = "Antique Nobleman's Signet Ring",
			mx = "Antique Nobleman's Signet Ring",
			de = "Antique Nobleman's Signet Ring",
			fr = "Antique Nobleman's Signet Ring",
			it = "Antique Nobleman's Signet Ring",
			pt = "Antique Nobleman's Signet Ring",
			ru = "Antique Nobleman's Signet Ring",
			ko = "Antique Nobleman's Signet Ring",
			cn = "Antique Nobleman's Signet Ring",
			tw = "Antique Nobleman's Signet Ring",
		},
	},
	[613324] = {
		readable = "Light-Infused Tinder Box",
		model = 5659419,
		text = {
			en = "Light-Infused Tinder Box",
			es = "Light-Infused Tinder Box",
			mx = "Light-Infused Tinder Box",
			de = "Light-Infused Tinder Box",
			fr = "Light-Infused Tinder Box",
			it = "Light-Infused Tinder Box",
			pt = "Light-Infused Tinder Box",
			ru = "Light-Infused Tinder Box",
			ko = "Light-Infused Tinder Box",
			cn = "Light-Infused Tinder Box",
			tw = "Light-Infused Tinder Box",
		},
	},
})
do ObjectDB[objectID] = objectData; end
