local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[660407] = {
		readable = "Missive from Malacrass",
		model = 1331239,
		text = {
			en = "Missive from Malacrass",
			es = "Missive from Malacrass",
			mx = "Missive from Malacrass",
			de = "Missive from Malacrass",
			fr = "Missive from Malacrass",
			it = "Missive from Malacrass",
			pt = "Missive from Malacrass",
			ru = "Missive from Malacrass",
			ko = "Missive from Malacrass",
			cn = "Missive from Malacrass",
			tw = "Missive from Malacrass",
		},
	},
	[660420] = {
		readable = "Fragment of Ulantu's Log 2",
		model = 1005460,
		text = {
			en = "Fragment of Ulantu's Log 2",
			es = "Fragment of Ulantu's Log 2",
			mx = "Fragment of Ulantu's Log 2",
			de = "Fragment of Ulantu's Log 2",
			fr = "Fragment of Ulantu's Log 2",
			it = "Fragment of Ulantu's Log 2",
			pt = "Fragment of Ulantu's Log 2",
			ru = "Fragment of Ulantu's Log 2",
			ko = "Fragment of Ulantu's Log 2",
			cn = "Fragment of Ulantu's Log 2",
			tw = "Fragment of Ulantu's Log 2",
		},
	},
	[660427] = {
		readable = "Lokago's Ledger",
		model = 791609,
		text = {
			en = "Lokago's Ledger",
			es = "Lokago's Ledger",
			mx = "Lokago's Ledger",
			de = "Lokago's Ledger",
			fr = "Lokago's Ledger",
			it = "Lokago's Ledger",
			pt = "Lokago's Ledger",
			ru = "Lokago's Ledger",
			ko = "Lokago's Ledger",
			cn = "Lokago's Ledger",
			tw = "Lokago's Ledger",
		},
	},
	[660431] = {
		readable = "Fragment of Ulantu's Log 3",
		model = 1005460,
		text = {
			en = "Fragment of Ulantu's Log 3",
			es = "Fragment of Ulantu's Log 3",
			mx = "Fragment of Ulantu's Log 3",
			de = "Fragment of Ulantu's Log 3",
			fr = "Fragment of Ulantu's Log 3",
			it = "Fragment of Ulantu's Log 3",
			pt = "Fragment of Ulantu's Log 3",
			ru = "Fragment of Ulantu's Log 3",
			ko = "Fragment of Ulantu's Log 3",
			cn = "Fragment of Ulantu's Log 3",
			tw = "Fragment of Ulantu's Log 3",
		},
	},
	[660985] = {
		readable = "Ulantu's Scout Pack",
		model = 5975174,
		text = {
			en = "Ulantu's Scout Pack",
			es = "Ulantu's Scout Pack",
			mx = "Ulantu's Scout Pack",
			de = "Ulantu's Scout Pack",
			fr = "Ulantu's Scout Pack",
			it = "Ulantu's Scout Pack",
			pt = "Ulantu's Scout Pack",
			ru = "Ulantu's Scout Pack",
			ko = "Ulantu's Scout Pack",
			cn = "Ulantu's Scout Pack",
			tw = "Ulantu's Scout Pack",
		},
	},
	[668589] = {
		readable = "Funerary Inscription",
		model = 6212412,
		text = {
			en = "Funerary Inscription",
			es = "Funerary Inscription",
			mx = "Funerary Inscription",
			de = "Funerary Inscription",
			fr = "Funerary Inscription",
			it = "Funerary Inscription",
			pt = "Funerary Inscription",
			ru = "Funerary Inscription",
			ko = "Funerary Inscription",
			cn = "Funerary Inscription",
			tw = "Funerary Inscription",
		},
	},
	[668590] = {
		readable = "Funerary Inscription",
		model = 6212412,
		text = {
			en = "Funerary Inscription",
			es = "Funerary Inscription",
			mx = "Funerary Inscription",
			de = "Funerary Inscription",
			fr = "Funerary Inscription",
			it = "Funerary Inscription",
			pt = "Funerary Inscription",
			ru = "Funerary Inscription",
			ko = "Funerary Inscription",
			cn = "Funerary Inscription",
			tw = "Funerary Inscription",
		},
	},
	[668591] = {
		readable = "Funerary Inscription",
		model = 6212412,
		text = {
			en = "Funerary Inscription",
			es = "Funerary Inscription",
			mx = "Funerary Inscription",
			de = "Funerary Inscription",
			fr = "Funerary Inscription",
			it = "Funerary Inscription",
			pt = "Funerary Inscription",
			ru = "Funerary Inscription",
			ko = "Funerary Inscription",
			cn = "Funerary Inscription",
			tw = "Funerary Inscription",
		},
	},
	[668593] = {
		readable = "Funerary Inscription",
		model = 6212412,
		text = {
			en = "Funerary Inscription",
			es = "Funerary Inscription",
			mx = "Funerary Inscription",
			de = "Funerary Inscription",
			fr = "Funerary Inscription",
			it = "Funerary Inscription",
			pt = "Funerary Inscription",
			ru = "Funerary Inscription",
			ko = "Funerary Inscription",
			cn = "Funerary Inscription",
			tw = "Funerary Inscription",
		},
	},
	[668594] = {
		readable = "Funerary Inscription",
		model = 6212412,
		text = {
			en = "Funerary Inscription",
			es = "Funerary Inscription",
			mx = "Funerary Inscription",
			de = "Funerary Inscription",
			fr = "Funerary Inscription",
			it = "Funerary Inscription",
			pt = "Funerary Inscription",
			ru = "Funerary Inscription",
			ko = "Funerary Inscription",
			cn = "Funerary Inscription",
			tw = "Funerary Inscription",
		},
	},
})
do ObjectDB[objectID] = objectData; end
