local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[580012] = {
		readable = "Tome of Binding",
		model = 5975157,
		text = {
			en = "Tome of Binding",
			es = "Tome of Binding",
			mx = "Tome of Binding",
			de = "Tome of Binding",
			fr = "Tome of Binding",
			it = "Tome of Binding",
			pt = "Tome of Binding",
			ru = "Tome of Binding",
			ko = "Tome of Binding",
			cn = "Tome of Binding",
			tw = "Tome of Binding",
		},
	},
	[580092] = {
		readable = "Brimming Void Canister",
		model = 6795671,
		text = {
			en = "Brimming Void Canister",
			es = "Brimming Void Canister",
			mx = "Brimming Void Canister",
			de = "Brimming Void Canister",
			fr = "Brimming Void Canister",
			it = "Brimming Void Canister",
			pt = "Brimming Void Canister",
			ru = "Brimming Void Canister",
			ko = "Brimming Void Canister",
			cn = "Brimming Void Canister",
			tw = "Brimming Void Canister",
		},
	},
	[580095] = {
		readable = "Null Stabilizer",
		model = 7136759,
		text = {
			en = "Null Stabilizer",
			es = "Null Stabilizer",
			mx = "Null Stabilizer",
			de = "Null Stabilizer",
			fr = "Null Stabilizer",
			it = "Null Stabilizer",
			pt = "Null Stabilizer",
			ru = "Null Stabilizer",
			ko = "Null Stabilizer",
			cn = "Null Stabilizer",
			tw = "Null Stabilizer",
		},
	},
	[580096] = {
		readable = "Voidway Energist",
		model = 7136760,
		text = {
			en = "Voidway Energist",
			es = "Voidway Energist",
			mx = "Voidway Energist",
			de = "Voidway Energist",
			fr = "Voidway Energist",
			it = "Voidway Energist",
			pt = "Voidway Energist",
			ru = "Voidway Energist",
			ko = "Voidway Energist",
			cn = "Voidway Energist",
			tw = "Voidway Energist",
		},
	},
	[580097] = {
		readable = "Singularity Forceps",
		model = 6980931,
		text = {
			en = "Singularity Forceps",
			es = "Singularity Forceps",
			mx = "Singularity Forceps",
			de = "Singularity Forceps",
			fr = "Singularity Forceps",
			it = "Singularity Forceps",
			pt = "Singularity Forceps",
			ru = "Singularity Forceps",
			ko = "Singularity Forceps",
			cn = "Singularity Forceps",
			tw = "Singularity Forceps",
		},
	},
	[581922] = {
		readable = "<span style=\"color: #A335EE\">Hidden Trove</span>",
		model = 5869302,
		text = {
			en = "<span style=\"color: #A335EE\">Hidden Trove</span>",
			es = "<span style=\"color: #A335EE\">Hidden Trove</span>",
			mx = "<span style=\"color: #A335EE\">Hidden Trove</span>",
			de = "<span style=\"color: #A335EE\">Hidden Trove</span>",
			fr = "<span style=\"color: #A335EE\">Hidden Trove</span>",
			it = "<span style=\"color: #A335EE\">Hidden Trove</span>",
			pt = "<span style=\"color: #A335EE\">Hidden Trove</span>",
			ru = "<span style=\"color: #A335EE\">Hidden Trove</span>",
			ko = "<span style=\"color: #A335EE\">Hidden Trove</span>",
			cn = "<span style=\"color: #A335EE\">Hidden Trove</span>",
			tw = "<span style=\"color: #A335EE\">Hidden Trove</span>",
		},
	},
	[583965] = {
		readable = "Maisara Vilevessel",
		model = 6904850,
		text = {
			en = "Maisara Vilevessel",
			es = "Maisara Vilevessel",
			mx = "Maisara Vilevessel",
			de = "Maisara Vilevessel",
			fr = "Maisara Vilevessel",
			it = "Maisara Vilevessel",
			pt = "Maisara Vilevessel",
			ru = "Maisara Vilevessel",
			ko = "Maisara Vilevessel",
			cn = "Maisara Vilevessel",
			tw = "Maisara Vilevessel",
		},
	},
	[583971] = {
		readable = "Stonewash Supplies",
		model = 1662185,
		text = {
			en = "Stonewash Supplies",
			es = "Stonewash Supplies",
		},
	},
})
do ObjectDB[objectID] = objectData; end
