local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[579193] = {
		readable = "Rusty Axe",
		model = 1005450,
		text = {
			en = "Rusty Axe",
			es = "Hacha oxidada",
			mx = "Hacha oxidada",
			de = "Rostige Axt",
			fr = "Hache rouillée",
			it = "Ascia Arrugginita",
			pt = "Machado Enferrujado",
			ru = "Ржавый топор",
			ko = "녹슨 도끼",
			cn = "生锈的斧子",
			tw = "生鏽的斧頭",
		},
	},
	[579233] = {
		readable = "Laments of Wey'nan--Part 1: Finding Hope",
		model = 6326920,
		text = {
			en = "Laments of Wey'nan--Part 1: Finding Hope",
			es = "Los lamentos de Wey'nan - Parte 1: En busca de esperanza",
			mx = "Lamentos de Wey'nan - Parte 1: En busca de esperanza",
			de = "Wey'nans Wehklagen, Teil 1: Ein Funke der Hoffnung",
			fr = "Plaintes de Wey’nan, partie 1 : en quête d’espoir",
			it = "Lamenti di Wey'nan - Parte 1: Trovare la Speranza",
			pt = "Lamentos de Wey'nan, Parte 1: Em Busca de Esperança",
			ru = "Плач Вей'нана – часть 1: поиски надежды",
			ko = "웨이난의 탄식 - 1부: 희망을 찾아서",
			cn = "威南的哀悼——第1部分：找希望",
			tw = "偉南之悲--第1部：尋找希望",
		},
	},
	[579234] = {
		readable = "Laments of Wey'nan--Part 2:  Hunting Purpose",
		model = 6326920,
		text = {
			en = "Laments of Wey'nan--Part 2:  Hunting Purpose",
			es = "Los lamentos de Wey'nan - Parte 2: Tras un propósito",
			mx = "[Laments of Wey'nan--Part 2:  Hunting Purpose]",
			de = "Wey'nans Wehklagen, Teil 2: Die Jagd nach Sinn",
			fr = "Plaintes de Wey’nan, partie 2 : finalité de la chasse",
			it = "Lamenti di Wey'nan - Parte 2: A Caccia di uno Scopo",
			pt = "Lamentos de Wey'nan, Parte 2: À Caça de um Propósito",
			ru = "Плач Вей'нана – часть 2: цель охоты",
			ko = "웨이난의 탄식 - 2부: 사냥의 목적",
			cn = "威南的哀悼——第2部分：狩猎使命",
			tw = "偉南之悲--第2部：追求使命",
		},
	},
	[579235] = {
		readable = "Laments of Wey'nan--Part 3: There Must Be More",
		model = 6326920,
		text = {
			en = "Laments of Wey'nan--Part 3: There Must Be More",
			es = "Los lamentos de Wey'nan - Parte 3: Debe de haber más",
			mx = "[Laments of Wey'nan--Part 3: There Must Be More]",
			de = "Wey'nans Wehklagen, Teil 3: Das kann nicht alles sein",
			fr = "Plaintes de Wey’nan, partie 3 : plus encore",
			it = "Lamenti di Wey'nan - Parte 3: Deve Esserci Altro",
			pt = "Lamentos de Wey'nan, Parte 3: Tem que Haver Algo Mais",
			ru = "Плач Вей'нана – часть 3: рано отступать",
			ko = "웨이난의 탄식 - 3부: 끝이 아닐 거야",
			cn = "威南的哀悼——第3部分：定能超越",
			tw = "偉南之悲--第3部：永無止境",
		},
	},
	[579242] = {
		readable = "Tending the Lands--Part 1: The Conflict",
		model = 6326920,
		text = {
			en = "Tending the Lands--Part 1: The Conflict",
			es = "Cuidando las tierras - Parte 1: El conflicto",
			mx = "Cuidado de las tierras - Parte 1: El conflicto",
			de = "Im Dienst des Landes, Teil 1: Der Konflikt",
			fr = "Préservation des terres, partie 1 : le conflit",
			it = "Vegliare sulle Terre - Parte 1: Il Conflitto",
			pt = "Cuidando da Terra, Parte 1: O Conflito",
			ru = "Забота о земле – часть 1: раздор",
			ko = "땅 돌보기 - 1부: 갈등",
			cn = "[Tending the Lands--Part 1: The Conflict]",
			tw = "照看土地--第1部：衝突",
		},
	},
	[579243] = {
		readable = "Tending the Lands--Part 2: The Plan",
		model = 6326920,
		text = {
			en = "Tending the Lands--Part 2: The Plan",
			es = "Cuidando las tierras - Parte 2: El plan",
			mx = "Cuidado de las tierras - Parte 2: El plan",
			de = "Im Dienst des Landes, Teil 2: Der Plan",
			fr = "Préservation des terres, partie 2 : le plan",
			it = "Vegliare sulle Terre - Parte 2: Il Piano",
			pt = "Cuidando da Terra, Parte 2: O Plano",
			ru = "Забота о земле – часть 2: план",
			ko = "땅 돌보기 - 2부: 계획",
			cn = "[Tending the Lands--Part 2: The Plan]",
			tw = "照看土地--第2部：計畫",
		},
	},
	[579244] = {
		readable = "Tending the Lands--Part 3: The Cycle",
		model = 6326920,
		text = {
			en = "Tending the Lands--Part 3: The Cycle",
			es = "Cuidando las tierras - Parte 3: El ciclo",
			mx = "Cuidado de las tierras - Parte 3: El ciclo",
			de = "Im Dienst des Landes, Teil 3: Der Kreislauf",
			fr = "Préservation des terres, partie 3 : le cycle",
			it = "Vegliare sulle Terre - Parte 3: Il Ciclo",
			pt = "Cuidando da Terra, Plano 3: O Ciclo",
			ru = "Забота о земле – часть 3: цикл",
			ko = "땅 돌보기 - 3부: 순환",
			cn = "[Tending the Lands--Part 3: The Cycle]",
			tw = "照看土地--第3部：循環",
		},
	},
	[582157] = {
		readable = "Spiritpaw Satchel",
		model = 1255202,
		text = {
			en = "Spiritpaw Satchel",
			es = "Bolsa de Pataespíritu",
			mx = "Bolsón de zarpánima",
			de = "Säckchen der Geisterpfoten",
			fr = "Sacoche patte-spirituelle",
			it = "Borsa degli Zampaspirito",
			pt = "Algibeira de Espiriturso",
			ru = "Сумка племени Призрачной Лапы",
			ko = "영혼발바닥 주머니",
			cn = "灵爪行囊",
			tw = "靈爪背袋",
		},
	},
	[584512] = {
		readable = "Nemesis Strongbox",
		model = 2907352,
		text = {
			en = "Nemesis Strongbox",
			es = "Caja fuerte de némesis",
			mx = "Caja fuerte de némesis",
			de = "Schließkassette der Nemesis",
			fr = "Coffre-fort de Némésis",
			it = "Forziere della Nemesi",
			pt = "Caixa-forte da Nêmesis",
			ru = "Сейф заклятого врага",
			ko = "원수의 금고",
			cn = "宿敌保险箱",
			tw = "死敵保險箱",
		},
	},
})
do ObjectDB[objectID] = objectData; end
