local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[639617] = {
		readable = "Tortollan Bottle",
		model = 1634604,
		text = {
			en = "Tortollan Bottle",
			es = "Tortollan Bottle",
			mx = "Tortollan Bottle",
			de = "Tortollan Bottle",
			fr = "Tortollan Bottle",
			it = "Tortollan Bottle",
			pt = "Tortollan Bottle",
			ru = "Tortollan Bottle",
			ko = "Tortollan Bottle",
			cn = "Tortollan Bottle",
			tw = "Tortollan Bottle",
		},
	},
	[639623] = {
		readable = "Tortollan Satchel",
		model = 1661561,
		text = {
			en = "Tortollan Satchel",
			es = "Tortollan Satchel",
			mx = "Tortollan Satchel",
			de = "Tortollan Satchel",
			fr = "Tortollan Satchel",
			it = "Tortollan Satchel",
			pt = "Tortollan Satchel",
			ru = "Tortollan Satchel",
			ko = "Tortollan Satchel",
			cn = "Tortollan Satchel",
			tw = "Tortollan Satchel",
		},
	},
	[639624] = {
		readable = "Tortollan Scroll",
		model = 1675073,
		text = {
			en = "Tortollan Scroll",
			es = "Tortollan Scroll",
			mx = "Tortollan Scroll",
			de = "Tortollan Scroll",
			fr = "Tortollan Scroll",
			it = "Tortollan Scroll",
			pt = "Tortollan Scroll",
			ru = "Tortollan Scroll",
			ko = "Tortollan Scroll",
			cn = "Tortollan Scroll",
			tw = "Tortollan Scroll",
		},
	},
	[639625] = {
		readable = "Tortollan Scroll Case",
		model = 1661563,
		text = {
			en = "Tortollan Scroll Case",
			es = "Tortollan Scroll Case",
			mx = "Tortollan Scroll Case",
			de = "Tortollan Scroll Case",
			fr = "Tortollan Scroll Case",
			it = "Tortollan Scroll Case",
			pt = "Tortollan Scroll Case",
			ru = "Tortollan Scroll Case",
			ko = "Tortollan Scroll Case",
			cn = "Tortollan Scroll Case",
			tw = "Tortollan Scroll Case",
		},
	},
	[642205] = {
		readable = "Forgotten Treasure",
		model = 6706182,
		text = {
			en = "Forgotten Treasure",
			es = "Forgotten Treasure",
			mx = "Forgotten Treasure",
			de = "Forgotten Treasure",
			fr = "Forgotten Treasure",
			it = "Forgotten Treasure",
			pt = "Forgotten Treasure",
			ru = "Forgotten Treasure",
			ko = "Forgotten Treasure",
			cn = "Forgotten Treasure",
			tw = "Forgotten Treasure",
		},
	},
	[642210] = {
		readable = "Forgotten Trinket",
		model = 6212420,
		text = {
			en = "Forgotten Trinket",
			es = "Forgotten Trinket",
			mx = "Forgotten Trinket",
			de = "Forgotten Trinket",
			fr = "Forgotten Trinket",
			it = "Forgotten Trinket",
			pt = "Forgotten Trinket",
			ru = "Forgotten Trinket",
			ko = "Forgotten Trinket",
			cn = "Forgotten Trinket",
			tw = "Forgotten Trinket",
		},
	},
})
do ObjectDB[objectID] = objectData; end
