local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[641984] = {
		readable = "Crumbling Urn",
		text = {
			en = "Crumbling Urn",
			es = "Crumbling Urn",
			mx = "Crumbling Urn",
			de = "Crumbling Urn",
			fr = "Crumbling Urn",
			it = "Crumbling Urn",
			pt = "Crumbling Urn",
			ru = "Crumbling Urn",
			ko = "Crumbling Urn",
			cn = "Crumbling Urn",
			tw = "Crumbling Urn",
		},
	},
	[642021] = {
		readable = "A Tarnished Amani Glaive",
		model = 6212428,
		text = {
			en = "A Tarnished Amani Glaive",
			es = "A Tarnished Amani Glaive",
			mx = "A Tarnished Amani Glaive",
			de = "A Tarnished Amani Glaive",
			fr = "A Tarnished Amani Glaive",
			it = "A Tarnished Amani Glaive",
			pt = "A Tarnished Amani Glaive",
			ru = "A Tarnished Amani Glaive",
			ko = "A Tarnished Amani Glaive",
			cn = "A Tarnished Amani Glaive",
			tw = "A Tarnished Amani Glaive",
		},
	},
	[642071] = {
		readable = "Jaktu's Cursed Blade",
		text = {
			en = "Jaktu's Cursed Blade",
			es = "Jaktu's Cursed Blade",
			mx = "Jaktu's Cursed Blade",
			de = "Jaktu's Cursed Blade",
			fr = "Jaktu's Cursed Blade",
			it = "Jaktu's Cursed Blade",
			pt = "Jaktu's Cursed Blade",
			ru = "Jaktu's Cursed Blade",
			ko = "Jaktu's Cursed Blade",
			cn = "Jaktu's Cursed Blade",
			tw = "Jaktu's Cursed Blade",
		},
	},
	[642307] = {
		readable = "Forgotten Mask",
		model = 6195676,
		text = {
			en = "Forgotten Mask",
			es = "Forgotten Mask",
			mx = "Forgotten Mask",
			de = "Forgotten Mask",
			fr = "Forgotten Mask",
			it = "Forgotten Mask",
			pt = "Forgotten Mask",
			ru = "Forgotten Mask",
			ko = "Forgotten Mask",
			cn = "Forgotten Mask",
			tw = "Forgotten Mask",
		},
	},
	[642316] = {
		readable = "Cracked Skull",
		model = 6153817,
		text = {
			en = "Cracked Skull",
			es = "Cracked Skull",
			mx = "Cracked Skull",
			de = "Cracked Skull",
			fr = "Cracked Skull",
			it = "Cracked Skull",
			pt = "Cracked Skull",
			ru = "Cracked Skull",
			ko = "Cracked Skull",
			cn = "Cracked Skull",
			tw = "Cracked Skull",
		},
	},
	[642322] = {
		readable = "Damaged Loa Trinket",
		text = {
			en = "Damaged Loa Trinket",
			es = "Damaged Loa Trinket",
			mx = "Damaged Loa Trinket",
			de = "Damaged Loa Trinket",
			fr = "Damaged Loa Trinket",
			it = "Damaged Loa Trinket",
			pt = "Damaged Loa Trinket",
			ru = "Damaged Loa Trinket",
			ko = "Damaged Loa Trinket",
			cn = "Damaged Loa Trinket",
			tw = "Damaged Loa Trinket",
		},
	},
	[642786] = {
		readable = "Zul'jan's Stash",
		text = {
			en = "Zul'jan's Stash",
			es = "Zul'jan's Stash",
			mx = "Zul'jan's Stash",
			de = "Zul'jan's Stash",
			fr = "Zul'jan's Stash",
			it = "Zul'jan's Stash",
			pt = "Zul'jan's Stash",
			ru = "Zul'jan's Stash",
			ko = "Zul'jan's Stash",
			cn = "Zul'jan's Stash",
			tw = "Zul'jan's Stash",
		},
	},
	[644654] = {
		readable = "Venomjade Necklace",
		text = {
			en = "Venomjade Necklace",
			es = "Venomjade Necklace",
			mx = "Venomjade Necklace",
			de = "Venomjade Necklace",
			fr = "Venomjade Necklace",
			it = "Venomjade Necklace",
			pt = "Venomjade Necklace",
			ru = "Venomjade Necklace",
			ko = "Venomjade Necklace",
			cn = "Venomjade Necklace",
			tw = "Venomjade Necklace",
		},
	},
})
do ObjectDB[objectID] = objectData; end
