local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[577796] = {
		readable = "Artisan's Cache",
		model = 6017293,
		text = {
			en = "Artisan's Cache",
			es = "Alijo de artesano",
			mx = "Alijo de artesano",
			de = "Truhe des Fachmanns",
			fr = "Cache d’artisan",
			it = "Cassa dell'Artigiano",
			pt = "Baú de Artífice",
			ru = "Тайник умельца",
			ko = "장인의 보관함",
			cn = "工匠之箱",
			tw = "工匠寶箱",
		},
	},
	[577797] = {
		readable = "Artisan's Cache",
		model = 6017293,
		text = {
			en = "Artisan's Cache",
			es = "Alijo de artesano",
			mx = "Alijo de artesano",
			de = "Truhe des Fachmanns",
			fr = "Cache d’artisan",
			it = "Cassa dell'Artigiano",
			pt = "Baú de Artífice",
			ru = "Тайник умельца",
			ko = "장인의 보관함",
			cn = "工匠之箱",
			tw = "工匠寶箱",
		},
	},
	[577798] = {
		readable = "Artisan's Cache",
		model = 6017293,
		text = {
			en = "Artisan's Cache",
			es = "Alijo de artesano",
			mx = "Alijo de artesano",
			de = "Truhe des Fachmanns",
			fr = "Cache d’artisan",
			it = "Cassa dell'Artigiano",
			pt = "Baú de Artífice",
			ru = "Тайник умельца",
			ko = "장인의 보관함",
			cn = "[Artisan's Cache]",
			tw = "[Artisan's Cache]",
		},
	},
	[577800] = {
		readable = "Artisan's Cache",
		model = 6017293,
		text = {
			en = "Artisan's Cache",
			es = "Alijo de artesano",
			mx = "Alijo de artesano",
			de = "Truhe des Fachmanns",
			fr = "Cache d’artisan",
			it = "Cassa dell'Artigiano",
			pt = "Baú de Artífice",
			ru = "Тайник умельца",
			ko = "장인의 보관함",
			cn = "工匠之箱",
			tw = "工匠寶箱",
		},
	},
	[578160] = {
		readable = "Ashwood Lumber",
		model = 6922313,
		text = {
			en = "Ashwood Lumber",
			es = "Madera de fresno",
			mx = "Madera de xiloceniza",
			de = "Aschenholz",
			fr = "Bois de frêne",
			it = "Legname di Legno Secco",
			pt = "Lenha de Freixo",
			ru = "Древесина ясеня",
			ko = "잿빛나무 목재",
			cn = "灰木木料",
			tw = "灰木木材",
		},
	},
	[579123] = {
		readable = "Words of Obayo--Part 1: The Flame",
		model = 6326920,
		text = {
			en = "Words of Obayo--Part 1: The Flame",
			es = "Palabras de Obayo - Parte 1: La Llama",
			mx = "Palabras de Obayo - Parte 1: La Llama",
			de = "Worte von Obayo, Teil 1: Die Flamme",
			fr = "Paroles d’Obayo, partie 1 : la flamme",
			it = "Parole di Obayo - Parte 1: La Fiamma",
			pt = "Palavras de Obayo, Parte 1: A Chama",
			ru = "Слова Обайо – часть 1: пламя",
			ko = "오바요의 진언 - 1부: 불꽃",
			cn = "奥巴约之训——第1部分：烈焰",
			tw = "歐巴悠之言--第1部：烈焰",
		},
	},
	[579130] = {
		readable = "Words of Obayo--Part 2: The Rift",
		model = 6326920,
		text = {
			en = "Words of Obayo--Part 2: The Rift",
			es = "Palabras de Obayo - Parte 2: La Falla",
			mx = "Palabras de Obayo - Parte 2: La Falla",
			de = "Worte von Obayo, Teil 2: Der Riss",
			fr = "Paroles d’Obayo, partie 2 : la faille",
			it = "Parole di Obayo - Parte 2: La Fenditura",
			pt = "Palavras de Obayo, Parte 2: A Fenda",
			ru = "Слова Обайо – часть 2: Провал",
			ko = "오바요의 진언 - 2부: 균열",
			cn = "奥巴约之训——第2部分：裂隙",
			tw = "歐巴悠之言--第2部：裂隙",
		},
	},
	[579131] = {
		readable = "Words of Obayo--Part 3: The Silence",
		model = 6326920,
		text = {
			en = "Words of Obayo--Part 3: The Silence",
			es = "Palabras de Obayo - Parte 3: El silencio",
			mx = "Palabras de Obayo - Parte 3: El silencio",
			de = "Worte von Obayo, Teil 3: Die Stille",
			fr = "Paroles d’Obayo, partie 3 : le silence",
			it = "Parole di Obayo - Parte 3: Il Silenzio",
			pt = "Palavras de Obayo, Parte 3: O Silêncio",
			ru = "Слова Обайо – часть 3: безмолвие",
			ko = "오바요의 진언 - 3부: 침묵",
			cn = "奥巴约之训——第3部分：沉默",
			tw = "歐巴悠之言--第3部：沉默",
		},
	},
	[579236] = {
		readable = "Echoes of Our Past--Part 1: Fading History",
		model = 6326920,
		text = {
			en = "Echoes of Our Past--Part 1: Fading History",
			es = "Ecos del pasado - Parte 1: Historia en desaparición",
			mx = "Ecos de nuestro pasado - Parte 1: El olvido de la historia",
			de = "Echos unserer Vergangenheit, Teil 1: Schwindende Geschichte",
			fr = "Échos de notre passé, partie 1 : histoire peu à peu oubliée",
			it = "Echi del Nostro Passato - Parte 1: La Storia Sbiadisce",
			pt = "Ecos do Nosso Passado, Parte 1: História Evanescente",
			ru = "Отголоски нашего прошлого – часть 1: позабытая история",
			ko = "과거의 메아리 - 1부: 흐려지는 역사",
			cn = "往昔回响——消逝的历史",
			tw = "過往的回音--第1部：褪色歷史",
		},
	},
	[579237] = {
		readable = "Echoes of Our Past--Part 2: Alndust",
		model = 6326920,
		text = {
			en = "Echoes of Our Past--Part 2: Alndust",
			es = "Ecos del pasado - Parte 2: Polvo de Aln",
			mx = "Ecos de nuestro pasado - Parte 2: Polvo de Aln",
			de = "Echos unserer Vergangenheit, Teil 2: Alnstaub",
			fr = "Échos de notre passé, partie 2 : poudre d’Aln",
			it = "Echi del Nostro Passato - Parte 2: Polvere di Aln",
			pt = "Ecos do Nosso Passado, Parte 2: Pó-de-aln",
			ru = "Отголоски нашего прошлого – часть 2: пыль Альн",
			ko = "과거의 메아리 - 2부: 알른가루",
			cn = "往昔回响——艾林之尘",
			tw = "過往的回音--第2部：艾恩之塵",
		},
	},
	[579238] = {
		readable = "Echoes of Our Past--Part 3: Dangerous Memories",
		model = 6326920,
		text = {
			en = "Echoes of Our Past--Part 3: Dangerous Memories",
			es = "Ecos del pasado - Parte 3: Recuerdos peligrosos",
			mx = "Ecos de nuestro pasado - Parte 3: Recuerdos peligrosos",
			de = "Echos unserer Vergangenheit, Teil 3: Gefährliche Erinnerungen",
			fr = "Échos de notre passé, partie 3: souvenirs dangereux",
			it = "Echi del Nostro Passato - Parte 3 : Ricordi Pericolosi",
			pt = "Ecos do Nosso Passado, Parte 3: Memórias Perigosas",
			ru = "Отголоски нашего прошлого – часть 3: опасные воспоминания",
			ko = "과거의 메아리 - 3부: 위험한 기억",
			cn = "往昔回响——危险的回忆",
			tw = "過往的回音--第3部：危險回憶",
		},
	},
	[579239] = {
		readable = "Seeker's Trail--Part 1: Call of Aln'hara",
		model = 6326920,
		text = {
			en = "Seeker's Trail--Part 1: Call of Aln'hara",
			es = "El camino del aspirante - Parte 1: La llamada de Aln'hara",
			mx = "El rastro del buscador - Parte 1: El llamado de Aln'hara",
			de = "Der Pfad des Suchers, Teil 1: Aln'haras Ruf",
			fr = "Voie de la recherche, partie 1 : appel d’Aln’hara",
			it = "Cammino del Cercatore - Parte 1: Richiamo di Aln'hara",
			pt = "O Rastro do Perscrutador, Parte 1: O Chamado de Aln'hara",
			ru = "В поисках следов – часть 1: зов Альн'ары",
			ko = "탐구자의 자취 - 1부: 알른하라의 부름",
			cn = "探求者之迹——第1部分：艾林哈籁的呼唤",
			tw = "追尋者之徑--第1部：艾恩哈拉的呼喚",
		},
	},
	[579240] = {
		readable = "Seeker's Trail--Part 2: Seeking Peace",
		model = 6326920,
		text = {
			en = "Seeker's Trail--Part 2: Seeking Peace",
			es = "El camino del aspirante - Parte 2: Buscando la paz",
			mx = "El rastro del buscador - Parte 2: En busca de la paz",
			de = "Der Pfad des Suchers, Teil 2: Die Suche nach Frieden",
			fr = "Voie de la recherche, partie 2 : en quête de paix",
			it = "Cammino del Cercatore - Parte 2: Ricerca della Pace",
			pt = "O Rastro do Perscrutador, Parte 2: Em Busca de Paz",
			ru = "В поисках следов – часть 2: стремление к покою",
			ko = "탐구자의 자취 - 2부: 평화를 찾아서",
			cn = "探求者之迹——第2部分：探求平静",
			tw = "追尋者之徑--第2部：尋求和平",
		},
	},
	[579241] = {
		readable = "Seeker's Trail--Part 3: Unending Mission",
		model = 6326920,
		text = {
			en = "Seeker's Trail--Part 3: Unending Mission",
			es = "El camino del aspirante - Parte 3: Misión sin fin",
			mx = "El rastro del buscador - Parte 3: Una misión interminable",
			de = "Der Pfad des Suchers, Teil 3: Mission ohne Ende",
			fr = "Voie de la recherche, partie 3 : mission sans fin",
			it = "Cammino del Cercatore - Parte 3: Missione Interminabile",
			pt = "O Rastro do Perscrutador, Parte 3: Missão sem Fim",
			ru = "В поисках следов – часть 3: вечное служение",
			ko = "탐구자의 자취 - 3부: 끝없는 임무",
			cn = "探求者之迹——第3部分：无尽的使命",
			tw = "追尋者之徑--第3部：無盡任務",
		},
	},
})
do ObjectDB[objectID] = objectData; end
