local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[571127] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571128] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571129] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571131] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571133] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571134] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571135] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571136] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571137] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
			cn = "Glowing Moth",
			tw = "Glowing Moth",
		},
	},
	[571140] = {
		readable = "Glowing Moth",
		model = 124932,
		text = {
			en = "Glowing Moth",
			es = "Glowing Moth",
			mx = "Glowing Moth",
			de = "Glowing Moth",
			fr = "Glowing Moth",
			it = "Glowing Moth",
			pt = "Glowing Moth",
			ru = "Glowing Moth",
			ko = "Glowing Moth",
		},
	},
})
do ObjectDB[objectID] = objectData; end
