local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[611269] = {
		readable = "Feathered Trinket",
		text = {
			en = "Feathered Trinket",
			es = "Feathered Trinket",
			mx = "Feathered Trinket",
			de = "Feathered Trinket",
			fr = "Feathered Trinket",
			it = "Feathered Trinket",
			pt = "Feathered Trinket",
			ru = "Feathered Trinket",
			ko = "Feathered Trinket",
			cn = "Feathered Trinket",
			tw = "Feathered Trinket",
		},
	},
	[612012] = {
		readable = "Tarnished Pearl",
		model = 2358262,
		text = {
			en = "Tarnished Pearl",
			es = "Tarnished Pearl",
			mx = "Tarnished Pearl",
			de = "Tarnished Pearl",
			fr = "Tarnished Pearl",
			it = "Tarnished Pearl",
			pt = "Tarnished Pearl",
			ru = "Tarnished Pearl",
			ko = "Tarnished Pearl",
			cn = "Tarnished Pearl",
			tw = "Tarnished Pearl",
		},
	},
	[618319] = {
		readable = "Yl'mul's Ribcage",
		model = 1634373,
		text = {
			en = "Yl'mul's Ribcage",
			es = "Yl'mul's Ribcage",
			mx = "Yl'mul's Ribcage",
			de = "Yl'mul's Ribcage",
			fr = "Yl'mul's Ribcage",
			it = "Yl'mul's Ribcage",
			pt = "Yl'mul's Ribcage",
			ru = "Yl'mul's Ribcage",
			ko = "Yl'mul's Ribcage",
			cn = "Yl'mul's Ribcage",
			tw = "Yl'mul's Ribcage",
		},
	},
	[618320] = {
		readable = "Yl'mul's Other Arm",
		model = 1634370,
		text = {
			en = "Yl'mul's Other Arm",
			es = "Yl'mul's Other Arm",
			mx = "Yl'mul's Other Arm",
			de = "Yl'mul's Other Arm",
			fr = "Yl'mul's Other Arm",
			it = "Yl'mul's Other Arm",
			pt = "Yl'mul's Other Arm",
			ru = "Yl'mul's Other Arm",
			ko = "Yl'mul's Other Arm",
			cn = "Yl'mul's Other Arm",
			tw = "Yl'mul's Other Arm",
		},
	},
	[618321] = {
		readable = "Yl'mul's Skull",
		model = 1634376,
		text = {
			en = "Yl'mul's Skull",
			es = "Yl'mul's Skull",
			mx = "Yl'mul's Skull",
			de = "Yl'mul's Skull",
			fr = "Yl'mul's Skull",
			it = "Yl'mul's Skull",
			pt = "Yl'mul's Skull",
			ru = "Yl'mul's Skull",
			ko = "Yl'mul's Skull",
			cn = "Yl'mul's Skull",
			tw = "Yl'mul's Skull",
		},
	},
	[619677] = {
		readable = "Sweetsaw Bloom",
		text = {
			en = "Sweetsaw Bloom",
			es = "Sweetsaw Bloom",
			mx = "Sweetsaw Bloom",
			de = "Sweetsaw Bloom",
			fr = "Sweetsaw Bloom",
			it = "Sweetsaw Bloom",
			pt = "Sweetsaw Bloom",
			ru = "Sweetsaw Bloom",
			ko = "Sweetsaw Bloom",
			cn = "Sweetsaw Bloom",
			tw = "Sweetsaw Bloom",
		},
	},
	[619683] = {
		readable = "Guarded Seabird Nest",
		model = 6739982,
		text = {
			en = "Guarded Seabird Nest",
			es = "Guarded Seabird Nest",
			mx = "Guarded Seabird Nest",
			de = "Guarded Seabird Nest",
			fr = "Guarded Seabird Nest",
			it = "Guarded Seabird Nest",
			pt = "Guarded Seabird Nest",
			ru = "Guarded Seabird Nest",
			ko = "Guarded Seabird Nest",
			cn = "Guarded Seabird Nest",
			tw = "Guarded Seabird Nest",
		},
	},
	[619768] = {
		readable = "Grisly Cod Pool",
		model = 219407,
		text = {
			en = "Grisly Cod Pool",
			es = "Grisly Cod Pool",
			mx = "Grisly Cod Pool",
			de = "Grisly Cod Pool",
			fr = "Grisly Cod Pool",
			it = "Grisly Cod Pool",
			pt = "Grisly Cod Pool",
			ru = "Grisly Cod Pool",
			ko = "Grisly Cod Pool",
			cn = "Grisly Cod Pool",
			tw = "Grisly Cod Pool",
		},
	},
	[619906] = {
		readable = "Abandoned Amani Privateer's Cache",
		model = 6195763,
		text = {
			en = "Abandoned Amani Privateer's Cache",
			es = "Abandoned Amani Privateer's Cache",
			mx = "Abandoned Amani Privateer's Cache",
			de = "Abandoned Amani Privateer's Cache",
			fr = "Abandoned Amani Privateer's Cache",
			it = "Abandoned Amani Privateer's Cache",
			pt = "Abandoned Amani Privateer's Cache",
			ru = "Abandoned Amani Privateer's Cache",
			ko = "Abandoned Amani Privateer's Cache",
			cn = "Abandoned Amani Privateer's Cache",
			tw = "Abandoned Amani Privateer's Cache",
		},
	},
})
do ObjectDB[objectID] = objectData; end
