local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[619908] = {
		readable = "Broken Urn",
		text = {
			en = "Broken Urn",
			es = "Broken Urn",
			mx = "Broken Urn",
			de = "Broken Urn",
			fr = "Broken Urn",
			it = "Broken Urn",
			pt = "Broken Urn",
			ru = "Broken Urn",
			ko = "Broken Urn",
			cn = "Broken Urn",
			tw = "Broken Urn",
		},
	},
	[619921] = {
		readable = "Waterlogged Crate",
		model = 6310282,
		text = {
			en = "Waterlogged Crate",
			es = "Waterlogged Crate",
			mx = "Waterlogged Crate",
			de = "Waterlogged Crate",
			fr = "Waterlogged Crate",
			it = "Waterlogged Crate",
			pt = "Waterlogged Crate",
			ru = "Waterlogged Crate",
			ko = "Waterlogged Crate",
			cn = "Waterlogged Crate",
			tw = "Waterlogged Crate",
		},
	},
	[622048] = {
		readable = "Journal of a Literate Lich",
		model = 1319077,
		text = {
			en = "Journal of a Literate Lich",
			es = "Journal of a Literate Lich",
			mx = "Journal of a Literate Lich",
			de = "Journal of a Literate Lich",
			fr = "Journal of a Literate Lich",
			it = "Journal of a Literate Lich",
			pt = "Journal of a Literate Lich",
			ru = "Journal of a Literate Lich",
			ko = "Journal of a Literate Lich",
			cn = "Journal of a Literate Lich",
			tw = "Journal of a Literate Lich",
		},
	},
	[628446] = {
		readable = "Jan'alai's Cinder",
		model = 615682,
		text = {
			en = "Jan'alai's Cinder",
			es = "Jan'alai's Cinder",
			mx = "Jan'alai's Cinder",
			de = "Jan'alai's Cinder",
			fr = "Jan'alai's Cinder",
			it = "Jan'alai's Cinder",
			pt = "Jan'alai's Cinder",
			ru = "Jan'alai's Cinder",
			ko = "Jan'alai's Cinder",
			cn = "Jan'alai's Cinder",
			tw = "Jan'alai's Cinder",
		},
	},
	[629421] = {
		readable = "Malfunctioning Staff",
		model = 2059988,
		text = {
			en = "Malfunctioning Staff",
			es = "Malfunctioning Staff",
			mx = "Malfunctioning Staff",
			de = "Malfunctioning Staff",
			fr = "Malfunctioning Staff",
			it = "Malfunctioning Staff",
			pt = "Malfunctioning Staff",
			ru = "Malfunctioning Staff",
			ko = "Malfunctioning Staff",
			cn = "Malfunctioning Staff",
			tw = "Malfunctioning Staff",
		},
	},
	[631027] = {
		readable = "Bowl of Innards",
		model = 1695271,
		text = {
			en = "Bowl of Innards",
			es = "Bowl of Innards",
			mx = "Bowl of Innards",
			de = "Bowl of Innards",
			fr = "Bowl of Innards",
			it = "Bowl of Innards",
			pt = "Bowl of Innards",
			ru = "Bowl of Innards",
			ko = "Bowl of Innards",
			cn = "Bowl of Innards",
			tw = "Bowl of Innards",
		},
	},
	[633653] = {
		readable = "Purified Egg",
		model = 1658900,
		text = {
			en = "Purified Egg",
			es = "Purified Egg",
			mx = "Purified Egg",
			de = "Purified Egg",
			fr = "Purified Egg",
			it = "Purified Egg",
			pt = "Purified Egg",
			ru = "Purified Egg",
			ko = "Purified Egg",
			cn = "Purified Egg",
			tw = "Purified Egg",
		},
	},
	[641565] = {
		readable = "Faintly Glowing Gem",
		model = 5778209,
		text = {
			en = "Faintly Glowing Gem",
			es = "Faintly Glowing Gem",
			mx = "Faintly Glowing Gem",
			de = "Faintly Glowing Gem",
			fr = "Faintly Glowing Gem",
			it = "Faintly Glowing Gem",
			pt = "Faintly Glowing Gem",
			ru = "Faintly Glowing Gem",
			ko = "Faintly Glowing Gem",
			cn = "Faintly Glowing Gem",
			tw = "Faintly Glowing Gem",
		},
	},
})
do ObjectDB[objectID] = objectData; end
