local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[644665] = {
		readable = "Ornate Bottle",
		model = 1608206,
		text = {
			en = "Ornate Bottle",
			es = "Ornate Bottle",
			mx = "Ornate Bottle",
			de = "Ornate Bottle",
			fr = "Ornate Bottle",
			it = "Ornate Bottle",
			pt = "Ornate Bottle",
			ru = "Ornate Bottle",
			ko = "Ornate Bottle",
			cn = "Ornate Bottle",
			tw = "Ornate Bottle",
		},
	},
	[644681] = {
		readable = "Stinking Vessel",
		text = {
			en = "Stinking Vessel",
			es = "Stinking Vessel",
			mx = "Stinking Vessel",
			de = "Stinking Vessel",
			fr = "Stinking Vessel",
			it = "Stinking Vessel",
			pt = "Stinking Vessel",
			ru = "Stinking Vessel",
			ko = "Stinking Vessel",
			cn = "Stinking Vessel",
			tw = "Stinking Vessel",
		},
	},
	[644791] = {
		readable = "Waterlogged Basket",
		text = {
			en = "Waterlogged Basket",
			es = "Waterlogged Basket",
			mx = "Waterlogged Basket",
			de = "Waterlogged Basket",
			fr = "Waterlogged Basket",
			it = "Waterlogged Basket",
			pt = "Waterlogged Basket",
			ru = "Waterlogged Basket",
			ko = "Waterlogged Basket",
			cn = "Waterlogged Basket",
			tw = "Waterlogged Basket",
		},
	},
	[644813] = {
		readable = "Smoldering Incense",
		model = 6153813,
		text = {
			en = "Smoldering Incense",
			es = "Smoldering Incense",
			mx = "Smoldering Incense",
			de = "Smoldering Incense",
			fr = "Smoldering Incense",
			it = "Smoldering Incense",
			pt = "Smoldering Incense",
			ru = "Smoldering Incense",
			ko = "Smoldering Incense",
			cn = "Smoldering Incense",
			tw = "Smoldering Incense",
		},
	},
	[645208] = {
		readable = "Sunken Diver's Chest",
		model = 6195763,
		text = {
			en = "Sunken Diver's Chest",
			es = "Sunken Diver's Chest",
			mx = "Sunken Diver's Chest",
			de = "Sunken Diver's Chest",
			fr = "Sunken Diver's Chest",
			it = "Sunken Diver's Chest",
			pt = "Sunken Diver's Chest",
			ru = "Sunken Diver's Chest",
			ko = "Sunken Diver's Chest",
			cn = "Sunken Diver's Chest",
			tw = "Sunken Diver's Chest",
		},
	},
	[645410] = {
		readable = "Fangbound Sack",
		text = {
			en = "Fangbound Sack",
			es = "Fangbound Sack",
			mx = "Fangbound Sack",
			de = "Fangbound Sack",
			fr = "Fangbound Sack",
			it = "Fangbound Sack",
			pt = "Fangbound Sack",
			ru = "Fangbound Sack",
			ko = "Fangbound Sack",
			cn = "Fangbound Sack",
			tw = "Fangbound Sack",
		},
	},
	[645422] = {
		readable = "Profane Ritual Spoils",
		text = {
			en = "Profane Ritual Spoils",
			es = "Profane Ritual Spoils",
			mx = "Profane Ritual Spoils",
			de = "Profane Ritual Spoils",
			fr = "Profane Ritual Spoils",
			it = "Profane Ritual Spoils",
			pt = "Profane Ritual Spoils",
			ru = "Profane Ritual Spoils",
			ko = "Profane Ritual Spoils",
			cn = "Profane Ritual Spoils",
			tw = "Profane Ritual Spoils",
		},
	},
	[645549] = {
		readable = "Grave of Someone Forgotten",
		model = 189528,
		text = {
			en = "Grave of Someone Forgotten",
			es = "Grave of Someone Forgotten",
			mx = "Grave of Someone Forgotten",
			de = "Grave of Someone Forgotten",
			fr = "Grave of Someone Forgotten",
			it = "Grave of Someone Forgotten",
			pt = "Grave of Someone Forgotten",
			ru = "Grave of Someone Forgotten",
			ko = "Grave of Someone Forgotten",
			cn = "Grave of Someone Forgotten",
			tw = "Grave of Someone Forgotten",
		},
	},
	[645553] = {
		readable = "Nameless Grave",
		text = {
			en = "Nameless Grave",
			es = "Nameless Grave",
			mx = "Nameless Grave",
			de = "Nameless Grave",
			fr = "Nameless Grave",
			it = "Nameless Grave",
			pt = "Nameless Grave",
			ru = "Nameless Grave",
			ko = "Nameless Grave",
			cn = "Nameless Grave",
			tw = "Nameless Grave",
		},
	},
	[648564] = {
		readable = "Vul'zahn's Smuggled Treasure",
		model = 6195763,
		text = {
			en = "Vul'zahn's Smuggled Treasure",
			es = "Vul'zahn's Smuggled Treasure",
			mx = "Vul'zahn's Smuggled Treasure",
			de = "Vul'zahn's Smuggled Treasure",
			fr = "Vul'zahn's Smuggled Treasure",
			it = "Vul'zahn's Smuggled Treasure",
			pt = "Vul'zahn's Smuggled Treasure",
			ru = "Vul'zahn's Smuggled Treasure",
			ko = "Vul'zahn's Smuggled Treasure",
			cn = "Vul'zahn's Smuggled Treasure",
			tw = "Vul'zahn's Smuggled Treasure",
		},
	},
})
do ObjectDB[objectID] = objectData; end
