local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[613847] = {
		readable = "Mirveda's Notes",
		model = 6025932,
		text = {
			en = "Mirveda's Notes",
			es = "Mirveda's Notes",
			mx = "Mirveda's Notes",
			de = "Mirveda's Notes",
			fr = "Mirveda's Notes",
			it = "Mirveda's Notes",
			pt = "Mirveda's Notes",
			ru = "Mirveda's Notes",
			ko = "Mirveda's Notes",
			cn = "Mirveda's Notes",
			tw = "Mirveda's Notes",
		},
	},
	[613850] = {
		readable = "Hawkstrider Husbandry: Unabridged Edition",
		model = 6081198,
		text = {
			en = "Hawkstrider Husbandry: Unabridged Edition",
			es = "Hawkstrider Husbandry: Unabridged Edition",
			mx = "Hawkstrider Husbandry: Unabridged Edition",
			de = "Hawkstrider Husbandry: Unabridged Edition",
			fr = "Hawkstrider Husbandry: Unabridged Edition",
			it = "Hawkstrider Husbandry: Unabridged Edition",
			pt = "Hawkstrider Husbandry: Unabridged Edition",
			ru = "Hawkstrider Husbandry: Unabridged Edition",
			ko = "Hawkstrider Husbandry: Unabridged Edition",
			cn = "Hawkstrider Husbandry: Unabridged Edition",
			tw = "Hawkstrider Husbandry: Unabridged Edition",
		},
	},
	[613861] = {
		readable = "Shrine of Dath'Remar",
		model = 5524217,
		text = {
			en = "Shrine of Dath'Remar",
			es = "Shrine of Dath'Remar",
			mx = "Shrine of Dath'Remar",
			de = "Shrine of Dath'Remar",
			fr = "Shrine of Dath'Remar",
			it = "Shrine of Dath'Remar",
			pt = "Shrine of Dath'Remar",
			ru = "Shrine of Dath'Remar",
			ko = "Shrine of Dath'Remar",
			cn = "Shrine of Dath'Remar",
			tw = "Shrine of Dath'Remar",
		},
	},
	[614483] = {
		readable = "Peculiar Cauldron",
		model = 6865595,
		text = {
			en = "Peculiar Cauldron",
			es = "Peculiar Cauldron",
			mx = "Peculiar Cauldron",
			de = "Peculiar Cauldron",
			fr = "Peculiar Cauldron",
			it = "Peculiar Cauldron",
			pt = "Peculiar Cauldron",
			ru = "Peculiar Cauldron",
			ko = "Peculiar Cauldron",
			cn = "Peculiar Cauldron",
			tw = "Peculiar Cauldron",
		},
	},
	[614636] = {
		readable = "Frostbitten Tabard",
		model = 5389582,
		text = {
			en = "Frostbitten Tabard",
			es = "Frostbitten Tabard",
			mx = "Frostbitten Tabard",
			de = "Frostbitten Tabard",
			fr = "Frostbitten Tabard",
			it = "Frostbitten Tabard",
			pt = "Frostbitten Tabard",
			ru = "Frostbitten Tabard",
			ko = "Frostbitten Tabard",
			cn = "Frostbitten Tabard",
			tw = "Frostbitten Tabard",
		},
	},
	[616052] = {
		readable = "Flame-Hardened Sap of Teldrassil",
		model = 4248598,
		text = {
			en = "Flame-Hardened Sap of Teldrassil",
			es = "Flame-Hardened Sap of Teldrassil",
			mx = "Flame-Hardened Sap of Teldrassil",
			de = "Flame-Hardened Sap of Teldrassil",
			fr = "Flame-Hardened Sap of Teldrassil",
			it = "Flame-Hardened Sap of Teldrassil",
			pt = "Flame-Hardened Sap of Teldrassil",
			ru = "Flame-Hardened Sap of Teldrassil",
			ko = "Flame-Hardened Sap of Teldrassil",
			cn = "Flame-Hardened Sap of Teldrassil",
			tw = "Flame-Hardened Sap of Teldrassil",
		},
	},
	[617232] = {
		readable = "Forgotten Practice Equipment",
		model = 1064189,
		text = {
			en = "Forgotten Practice Equipment",
			es = "Forgotten Practice Equipment",
			mx = "Forgotten Practice Equipment",
			de = "Forgotten Practice Equipment",
			fr = "Forgotten Practice Equipment",
			it = "Forgotten Practice Equipment",
			pt = "Forgotten Practice Equipment",
			ru = "Forgotten Practice Equipment",
			ko = "Forgotten Practice Equipment",
			cn = "Forgotten Practice Equipment",
			tw = "Forgotten Practice Equipment",
		},
	},
})
do ObjectDB[objectID] = objectData; end
