local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[654991] = {
		readable = "Cracked Canopic Jar",
		model = 6904849,
		text = {
			en = "Cracked Canopic Jar",
			es = "Cracked Canopic Jar",
			mx = "Cracked Canopic Jar",
			de = "Cracked Canopic Jar",
			fr = "Cracked Canopic Jar",
			it = "Cracked Canopic Jar",
			pt = "Cracked Canopic Jar",
			ru = "Cracked Canopic Jar",
			ko = "Cracked Canopic Jar",
			cn = "Cracked Canopic Jar",
			tw = "Cracked Canopic Jar",
		},
	},
	[656039] = {
		readable = "Venom-Clotted Bauble",
		text = {
			en = "Venom-Clotted Bauble",
			es = "Venom-Clotted Bauble",
			mx = "Venom-Clotted Bauble",
			de = "Venom-Clotted Bauble",
			fr = "Venom-Clotted Bauble",
			it = "Venom-Clotted Bauble",
			pt = "Venom-Clotted Bauble",
			ru = "Venom-Clotted Bauble",
			ko = "Venom-Clotted Bauble",
			cn = "Venom-Clotted Bauble",
			tw = "Venom-Clotted Bauble",
		},
	},
	[656044] = {
		readable = "Singing Shell",
		model = 2843041,
		text = {
			en = "Singing Shell",
			es = "Singing Shell",
			mx = "Singing Shell",
			de = "Singing Shell",
			fr = "Singing Shell",
			it = "Singing Shell",
			pt = "Singing Shell",
			ru = "Singing Shell",
			ko = "Singing Shell",
			cn = "Singing Shell",
			tw = "Singing Shell",
		},
	},
	[656135] = {
		readable = "Slumbering Starfish",
		text = {
			en = "Slumbering Starfish",
			es = "Slumbering Starfish",
			mx = "Slumbering Starfish",
			de = "Slumbering Starfish",
			fr = "Slumbering Starfish",
			it = "Slumbering Starfish",
			pt = "Slumbering Starfish",
			ru = "Slumbering Starfish",
			ko = "Slumbering Starfish",
			cn = "Slumbering Starfish",
			tw = "Slumbering Starfish",
		},
	},
	[656678] = {
		readable = "Possessed Vase",
		model = 6706182,
		text = {
			en = "Possessed Vase",
			es = "Possessed Vase",
			mx = "Possessed Vase",
			de = "Possessed Vase",
			fr = "Possessed Vase",
			it = "Possessed Vase",
			pt = "Possessed Vase",
			ru = "Possessed Vase",
			ko = "Possessed Vase",
			cn = "Possessed Vase",
			tw = "Possessed Vase",
		},
	},
	[660393] = {
		readable = "Fragment of Ulantu's Log 1",
		model = 1005460,
		text = {
			en = "Fragment of Ulantu's Log 1",
			es = "Fragment of Ulantu's Log 1",
			mx = "Fragment of Ulantu's Log 1",
			de = "Fragment of Ulantu's Log 1",
			fr = "Fragment of Ulantu's Log 1",
			it = "Fragment of Ulantu's Log 1",
			pt = "Fragment of Ulantu's Log 1",
			ru = "Fragment of Ulantu's Log 1",
			ko = "Fragment of Ulantu's Log 1",
			cn = "Fragment of Ulantu's Log 1",
			tw = "Fragment of Ulantu's Log 1",
		},
	},
	[660399] = {
		readable = "Experiment Notes",
		model = 5007028,
		text = {
			en = "Experiment Notes",
			es = "Experiment Notes",
			mx = "Experiment Notes",
			de = "Experiment Notes",
			fr = "Experiment Notes",
			it = "Experiment Notes",
			pt = "Experiment Notes",
			ru = "Experiment Notes",
			ko = "Experiment Notes",
			cn = "Experiment Notes",
			tw = "Experiment Notes",
		},
	},
})
do ObjectDB[objectID] = objectData; end
