local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[572033] = {
		readable = "Evergreen Vine",
		model = 651497,
		text = {
			en = "Evergreen Vine",
			es = "Parra de siempreverde",
			mx = "Vid siempreverde",
			de = "Immergrüne Ranke",
			fr = "Vigne sempervirente",
			it = "Viticcio Sempreverde",
			pt = "Trepadeira Sempre-verde",
			ru = "Вечнозеленая лоза",
			ko = "사철나무 덩굴",
			cn = "常青藤蔓",
			tw = "長青藤蔓",
		},
	},
	[572036] = {
		readable = "Heavy Anchor",
		model = 1611709,
		text = {
			en = "Heavy Anchor",
			es = "Ancla pesada",
			mx = "Ancla pesada",
			de = "Schwerer Anker",
			fr = "Ancre lourde",
			it = "Ancora Pesante",
			pt = "Âncora Pesada",
			ru = "Тяжелый якорь",
			ko = "무거운 닻",
			cn = "沉重的锚",
			tw = "重錨",
		},
	},
	[572037] = {
		readable = "Sandy Tapestry",
		model = 1674722,
		text = {
			en = "Sandy Tapestry",
			es = "Tapiz arenoso",
			mx = "Tapiz arenoso",
			de = "Sandiger Wandteppich",
			fr = "Tapisserie sableuse",
			it = "Arazzo Sabbioso",
			pt = "Tapeçaria Arenosa",
			ru = "Песчаный гобелен",
			ko = "모래투성이 융단",
			cn = "染沙的挂毯",
			tw = "滿布沙塵的掛毯",
		},
	},
	[572446] = {
		readable = "Scarred Spear",
		model = 943686,
		text = {
			en = "Scarred Spear",
			es = "Lanza cicatrícea",
			mx = "Lanza desgarrada",
			de = "Verschrammter Speer",
			fr = "Lance griffée",
			it = "Lancia Sfregiata",
			pt = "Lança Marcada",
			ru = "Иссеченное копье",
			ko = "흉터투성이 창",
			cn = "战痕长矛",
			tw = "傷痕之矛",
		},
	},
	[572450] = {
		readable = "Ancient Zandalari Scroll",
		model = 774267,
		text = {
			en = "Ancient Zandalari Scroll",
			es = "Pergamino Zandalari antiguo",
			mx = "Pergamino Zandalari antiguo",
			de = "Uralte Zandalarischriftrolle",
			fr = "Parchemin zandalari antique",
			it = "Antica Pergamena degli Zandalari",
			pt = "Pergaminho Zandalari Ancestral",
			ru = "Древний зандаларский свиток",
			ko = "고대 잔달라 두루마리",
			cn = "古代赞达拉卷轴",
			tw = "遠古贊達拉卷軸",
		},
	},
	[572451] = {
		readable = "Evergreen Vine",
		model = 651497,
		text = {
			en = "Evergreen Vine",
			es = "Parra de siempreverde",
			mx = "Vid siempreverde",
			de = "Immergrüne Ranke",
			fr = "Vigne sempervirente",
			it = "Viticcio Sempreverde",
			pt = "Trepadeira Sempre-verde",
			ru = "Вечнозеленая лоза",
			ko = "사철나무 덩굴",
			cn = "常青藤蔓",
			tw = "長青藤蔓",
		},
	},
	[572454] = {
		readable = "Weathered Tome",
		model = 985164,
		text = {
			en = "Weathered Tome",
			es = "Tomo erosionado",
			mx = "Tomo desgastado",
			de = "Verwitterter Foliant",
			fr = "Tome dégradé",
			it = "Tomo Logoro",
			pt = "Tomo Surrado",
			ru = "Потертый фолиант",
			ko = "마모된 고서",
			cn = "饱经风霜的书典",
			tw = "破舊的秘典",
		},
	},
	[572455] = {
		readable = "Heavy Anchor",
		model = 1611709,
		text = {
			en = "Heavy Anchor",
			es = "Ancla pesada",
			mx = "Ancla pesada",
			de = "Schwerer Anker",
			fr = "Ancre lourde",
			it = "Ancora Pesante",
			pt = "Âncora Pesada",
			ru = "Тяжелый якорь",
			ko = "무거운 닻",
			cn = "沉重的锚",
			tw = "重錨",
		},
	},
	[572456] = {
		readable = "Sandy Tapestry",
		model = 1674722,
		text = {
			en = "Sandy Tapestry",
			es = "Tapiz arenoso",
			mx = "Tapiz arenoso",
			de = "Sandiger Wandteppich",
			fr = "Tapisserie sableuse",
			it = "Arazzo Sabbioso",
			pt = "Tapeçaria Arenosa",
			ru = "Песчаный гобелен",
			ko = "모래투성이 융단",
			cn = "染沙的挂毯",
			tw = "滿布沙塵的掛毯",
		},
	},
	[579201] = {
		readable = "Awe'ohna's Path--Part 1: Questions",
		model = 6326920,
		text = {
			en = "Awe'ohna's Path--Part 1: Questions",
			es = "El camino de Awe'ohna - Parte 1: Preguntas",
			mx = "El camino de Awe'ohna - Parte 1: Preguntas",
			de = "Awe'ohnas Pfad, Teil 1: Fragen",
			fr = "Parcours d’Awe’ohna, partie 1: Questions",
			it = "Cammino di Awe'ohna - Parte 1: Domande",
			pt = "O Caminho de Pasm'ohn, Parte 1: Perguntas",
			ru = "Путь Аве'оны – часть 1: Вопросы",
			ko = "아웨오나의 길 - 1부: 의문",
			cn = "奥欧娜之路——第1部分：疑问",
			tw = "歐荷納之路--第1部：提問",
		},
	},
	[579202] = {
		readable = "Awe'ohna's Path--Part 2: Answers",
		model = 6326920,
		text = {
			en = "Awe'ohna's Path--Part 2: Answers",
			es = "El camino de Awe'ohna - Parte 2: Respuestas",
			mx = "El camino de Awe'ohna - Parte 2: Respuestas",
			de = "Awe'ohnas Pfad, Teil 2: Antworten",
			fr = "Parcours d’Awe’ohna, partie 2: Réponse",
			it = "Cammino di Awe'ohna - Parte 2: Risposte",
			pt = "O Caminho de Pasm'ohn, Parte 2: Respostas",
			ru = "Путь Аве'оны – часть 2: Ответы",
			ko = "아웨오나의 길 - 2부: 정답",
			cn = "奥欧娜之路——第2部分：解答",
			tw = "歐荷納之路--第2部：解答",
		},
	},
	[579203] = {
		readable = "Awe'ohna's Path--Part 3: The Cradle",
		model = 6326920,
		text = {
			en = "Awe'ohna's Path--Part 3: The Cradle",
			es = "El camino de Awe'ohna - Parte 3: La Cuna",
			mx = "El camino de Awe'ohna - Parte 3: La Cuna",
			de = "Awe'ohnas Pfad, Teil 3: Die Wiege",
			fr = "Parcours d’Awe’ohna, partie 3 : le Berceau",
			it = "Cammino di Awe'ohna - Parte 3: La Culla",
			pt = "O Caminho de Pasm'ohn, Parte 3: O Berço",
			ru = "Путь Аве'оны – часть 3: Колыбель",
			ko = "아웨오나의 길 - 3부: 요람",
			cn = "奥欧娜之路——第3部分：摇篮",
			tw = "歐荷納之路--第3部：育所",
		},
	},
})
do ObjectDB[objectID] = objectData; end
