name: Bug Report
description: Report an issue or something not working correctly.
labels: ["Addon Bug"]

body:
  - type: dropdown
    id: flavour
    attributes:
      label: "Which flavo(u)r(s) of WoW are you using?"
      description: "Select all applicable versions of World of Warcraft."
      multiple: true
      options:
        - "Retail"
        - "MoP Classic"
        - "WotLK Classic"
        - "Classic Era"
        - "Hardcore"
        - "Season of Discovery"
        - "Anniversary Realms"
        - "Hardcore Anniversary Realms"
    validations:
      required: true

  - type: dropdown
    id: realm
    attributes:
      label: "Which server realm(s) are you in?"
      description: "Select the region(s) where you encountered the issue."
      multiple: true
      options:
        - "US"
        - "EU"
        - "KR"
        - "TW"
        - "CN"

  - type: input
    id: wow_build
    attributes:
      label: "WoW Client Build"
      description: "Provide the specific WoW build (e.g., from `/dump GetBuildInfo()`[1] & [2] or found on the login screen)."
      placeholder: "e.g., 10.1.7.51000"
    validations:
      required: true

  - type: dropdown
    id: wow_event
    attributes:
      label: "WoW Event"
      description: "Are you participating in special events like the Legion remix?"
      options:
        - "Mainline"
        - "Legion remix"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: wow_language
    attributes:
      label: "WoW Client Language"
      description: "Select the language of your WoW client."
      options:
        - "enUS"
        - "deDE"
        - "esES"
        - "esMX"
        - "frFR"
        - "itIT"
        - "koKR"
        - "ptBR"
        - "ruRU"
        - "zhCN"
        - "zhTW"
    validations:
      required: true

  - type: dropdown
    id: att_version
    attributes:
      label: "ATT Version"
      description: "Select the version of ATT you are using."
      options:
        - "Latest release"
        - "Latest alpha"
        - "git"
    validations:
      required: true

  - type: input
    id: att_build
    attributes:
      label: "ATT Build Number"
      description: "Provide the specific ATT build (e.g., from `/dump ATTC.Version` or addon info)."
      placeholder: "e.g., 4.1.11(release) / 4.1.11-34-g9b96b53(alpha)"
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: "Describe the Bug"
      description: "What isn't working? What did you expect to happen?"
      placeholder: "Describe the issue here..."
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshot"
      description: "Attach a screenshot or image that helps illustrate the issue."
      placeholder: "Drop image(s) here or paste links..."

  - type: textarea
    id: reproduce_steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide detailed steps so we can reproduce the issue:\n1. Go to '...'\n2. Click '...'\n3. Observe the bug."
      placeholder: "List steps here..."
    validations:
      required: true

  - type: textarea
    id: lua_errors
    attributes:
      label: "Lua Errors"
      description: "Include any Lua error messages (from BugSack or `/console scriptErrors 1`)."
      placeholder: "Paste error logs here..."

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other information that might help us diagnose the issue."
      placeholder: "Anything else to add?"