name: Parser

# Controls when the action will run.
on:
  # Triggers the workflow on each push event
  push:
    paths:
      - '.contrib/Parser/**'
  # Triggers the workflow on each pull request event
  pull_request:
    paths:
      - '.contrib/Parser/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5

      - name: Database Parser for Retail
        timeout-minutes: 5
        continue-on-error: true
        run: |
          cd .contrib/Parser
          "Parser.exe" auto baseconfig=.config/retail/retail.config
        shell: cmd

      - name: Database Parser for Classic Era
        timeout-minutes: 5
        continue-on-error: true
        run: |
          cd .contrib/Parser
          "Parser.exe" auto config=".config/classic/01 - Classic Era.config"
        shell: cmd

      - name: Database Parser for Season of Discovery
        timeout-minutes: 5
        continue-on-error: true
        run: |
          cd .contrib/Parser
          "Parser.exe" auto config=".config/classic/01 - Classic SOD.config"
        shell: cmd

      - name: Database Parser for The Burning Crusade
        timeout-minutes: 5
        continue-on-error: true
        run: |
          cd .contrib/Parser
          "Parser.exe" auto config=".config/classic/02 - TBC.config"
        shell: cmd

      - name: Database Parser for Wrath of the Lich King
        timeout-minutes: 5
        continue-on-error: true
        run: |
          cd .contrib/Parser
          "Parser.exe" auto config=".config/classic/03 - Wrath.config"
        shell: cmd

      - name: Database Parser for Cataclysm
        timeout-minutes: 5
        continue-on-error: true
        run: |
          cd .contrib/Parser
          "Parser.exe" auto config=".config/classic/04 - Cataclysm.config"
        shell: cmd

      - name: Database Parser for Mists of Pandaria
        timeout-minutes: 5
        continue-on-error: true
        run: |
          cd .contrib/Parser
          "Parser.exe" auto config=".config/classic/05 - Mists of Pandaria.config"
        shell: cmd

      - name: Full Success Check
        if: success()
        run: |
          echo "All Versions Parsed successfully!"

      - uses: actions/upload-artifact@v4
        with:
            name: db  # Artifact name
            path: db/  # File path to upload
            retention-days: 7
